# Form implementation generated from reading ui file 'addmember_interface.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_addmember_dialog(object):
    def setupUi(self, addmember_dialog):
        addmember_dialog.setObjectName("addmember_dialog")
        addmember_dialog.resize(616, 502)
        addmember_dialog.setStyleSheet("QDialog{\n"
"    background-color: #edf4fa;\n"
"}\n"
"\n"
"QFrame {\n"
"    background-color: #FFFFFF;\n"
"    border: 1px solid #FFFFFF;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QLabel    {\n"
"    font-family: \"Poppins\", sans-serif;\n"
"    font-weight: bold;\n"
"    font-size: 8pt;\n"
"    color: #92979d;\n"
"    border: none;\n"
"}\n"
"\n"
"QLineEdit, QListWidget {\n"
"    border: 1px solid #edf4fa;\n"
"    border-radius: 8px;\n"
"    padding: 4px;\n"
"    font-family: \"Poppins\", sans-serif;\n"
"    font-weight: normal;\n"
"    font-size: 10pt;\n"
"    background-color: #edf4fa;\n"
"    color: #333;\n"
"}\n"
"\n"
"QLineEdit:focus, QListWidget:focus {\n"
"    border: none;\n"
"    background-color: #b8e6d9;\n"
"}\n"
"\n"
"QDateTimeEdit::down-arrow {\n"
"    image: url(:/icons/icons/chevron-down_black.svg);\n"
"    width: 10px;\n"
"    height: 10px;\n"
"}\n"
"\n"
"QDateTimeEdit::up-arrow {\n"
"    image: url(:/icons/icons/chevron-up_black.svg);\n"
"    width: 10px;\n"
"    height: 10px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #01c28e;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    color: #FFFFFF;\n"
"    text-align: center;\n"
"    font-family: \"Poppins\", sans-serif;\n"
"    font-size: 10pt;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"Line {\n"
"    background-color: #92979d;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: url(:/icons/icons/chevron-down_black.svg);\n"
"    width: 20px;\n"
"    height: 20px;\n"
"}\n"
"\n"
"#addmember_label{\n"
"    color: #01c28e;\n"
"    font-size: 20pt;\n"
"}")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(addmember_dialog)
        self.verticalLayout_11.setContentsMargins(15, 15, 15, 15)
        self.verticalLayout_11.setSpacing(10)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.member_info = QtWidgets.QFrame(parent=addmember_dialog)
        self.member_info.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.member_info.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.member_info.setObjectName("member_info")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.member_info)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.addmember_label = QtWidgets.QLabel(parent=self.member_info)
        self.addmember_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.addmember_label.setObjectName("addmember_label")
        self.gridLayout_2.addWidget(self.addmember_label, 0, 0, 1, 2)
        self.member_name_frame = QtWidgets.QFrame(parent=self.member_info)
        self.member_name_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.member_name_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.member_name_frame.setObjectName("member_name_frame")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.member_name_frame)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.member_name = QtWidgets.QLabel(parent=self.member_name_frame)
        self.member_name.setObjectName("member_name")
        self.verticalLayout_6.addWidget(self.member_name)
        self.member_name_info = QtWidgets.QLineEdit(parent=self.member_name_frame)
        self.member_name_info.setText("")
        self.member_name_info.setObjectName("member_name_info")
        self.verticalLayout_6.addWidget(self.member_name_info)
        self.gridLayout_2.addWidget(self.member_name_frame, 1, 0, 1, 1)
        self.member_id_frame = QtWidgets.QFrame(parent=self.member_info)
        self.member_id_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.member_id_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.member_id_frame.setObjectName("member_id_frame")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.member_id_frame)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.member_id = QtWidgets.QLabel(parent=self.member_id_frame)
        self.member_id.setObjectName("member_id")
        self.verticalLayout_7.addWidget(self.member_id)
        self.member_id_info = QtWidgets.QLineEdit(parent=self.member_id_frame)
        self.member_id_info.setText("")
        self.member_id_info.setObjectName("member_id_info")
        self.verticalLayout_7.addWidget(self.member_id_info)
        self.gridLayout_2.addWidget(self.member_id_frame, 1, 1, 1, 1)
        self.member_email_frame = QtWidgets.QFrame(parent=self.member_info)
        self.member_email_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.member_email_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.member_email_frame.setObjectName("member_email_frame")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.member_email_frame)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.member_email = QtWidgets.QLabel(parent=self.member_email_frame)
        self.member_email.setObjectName("member_email")
        self.verticalLayout_8.addWidget(self.member_email)
        self.member_email_info = QtWidgets.QLineEdit(parent=self.member_email_frame)
        self.member_email_info.setText("")
        self.member_email_info.setObjectName("member_email_info")
        self.verticalLayout_8.addWidget(self.member_email_info)
        self.gridLayout_2.addWidget(self.member_email_frame, 2, 0, 1, 2)
        self.member_project_frame = QtWidgets.QFrame(parent=self.member_info)
        self.member_project_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.member_project_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.member_project_frame.setObjectName("member_project_frame")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.member_project_frame)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.member_project = QtWidgets.QLabel(parent=self.member_project_frame)
        self.member_project.setObjectName("member_project")
        self.verticalLayout_9.addWidget(self.member_project)
        self.member_project_info = QtWidgets.QListWidget(parent=self.member_project_frame)
        self.member_project_info.setObjectName("member_project_info")
        self.verticalLayout_9.addWidget(self.member_project_info)
        self.gridLayout_2.addWidget(self.member_project_frame, 3, 0, 1, 1)
        self.member_task_frame = QtWidgets.QFrame(parent=self.member_info)
        self.member_task_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.member_task_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.member_task_frame.setObjectName("member_task_frame")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.member_task_frame)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.member_task = QtWidgets.QLabel(parent=self.member_task_frame)
        self.member_task.setObjectName("member_task")
        self.verticalLayout_10.addWidget(self.member_task)
        self.member_task_info = QtWidgets.QListWidget(parent=self.member_task_frame)
        self.member_task_info.setObjectName("member_task_info")
        self.verticalLayout_10.addWidget(self.member_task_info)
        self.gridLayout_2.addWidget(self.member_task_frame, 3, 1, 1, 1)
        self.verticalLayout_11.addWidget(self.member_info)
        self.hline = QtWidgets.QFrame(parent=addmember_dialog)
        self.hline.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.hline.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.hline.setObjectName("hline")
        self.verticalLayout_11.addWidget(self.hline)
        self.frame = QtWidgets.QFrame(parent=addmember_dialog)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.task_save_button = QtWidgets.QPushButton(parent=self.frame)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/save.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.task_save_button.setIcon(icon)
        self.task_save_button.setObjectName("task_save_button")
        self.horizontalLayout.addWidget(self.task_save_button)
        self.task_clear_button = QtWidgets.QPushButton(parent=self.frame)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/delete.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.task_clear_button.setIcon(icon1)
        self.task_clear_button.setObjectName("task_clear_button")
        self.horizontalLayout.addWidget(self.task_clear_button)
        self.task_cancel_button = QtWidgets.QPushButton(parent=self.frame)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/x-square.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.task_cancel_button.setIcon(icon2)
        self.task_cancel_button.setObjectName("task_cancel_button")
        self.horizontalLayout.addWidget(self.task_cancel_button)
        self.verticalLayout_11.addWidget(self.frame)

        self.retranslateUi(addmember_dialog)
        QtCore.QMetaObject.connectSlotsByName(addmember_dialog)

    def retranslateUi(self, addmember_dialog):
        _translate = QtCore.QCoreApplication.translate
        addmember_dialog.setWindowTitle(_translate("addmember_dialog", "Dialog"))
        self.addmember_label.setText(_translate("addmember_dialog", "MEMBER"))
        self.member_name.setText(_translate("addmember_dialog", "FULL NAME"))
        self.member_name_info.setPlaceholderText(_translate("addmember_dialog", "Enter full name"))
        self.member_id.setText(_translate("addmember_dialog", "MEMBER ID"))
        self.member_id_info.setPlaceholderText(_translate("addmember_dialog", "NNNN-NNNN"))
        self.member_email.setText(_translate("addmember_dialog", "EMAIL"))
        self.member_email_info.setPlaceholderText(_translate("addmember_dialog", "example@gmail.com"))
        self.member_project.setText(_translate("addmember_dialog", "PROJECT"))
        self.member_task.setText(_translate("addmember_dialog", "TASK"))
        self.task_save_button.setText(_translate("addmember_dialog", "Save"))
        self.task_clear_button.setText(_translate("addmember_dialog", "Clear"))
        self.task_cancel_button.setText(_translate("addmember_dialog", "Cancel"))
