# Form implementation generated from reading ui file 'addproject_interface.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_addproject_dialog(object):
    def setupUi(self, addproject_dialog):
        addproject_dialog.setObjectName("addproject_dialog")
        addproject_dialog.resize(616, 464)
        addproject_dialog.setStyleSheet("QDialog{\n"
"    background-color: #edf4fa;\n"
"}\n"
"\n"
"QFrame {\n"
"    background-color: #FFFFFF;\n"
"    border: 1px solid #FFFFFF;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QLabel    {\n"
"    font-family: \"Poppins\", sans-serif;\n"
"    font-weight: bold;\n"
"    font-size: 8pt;\n"
"    color: #92979d;\n"
"    border: none;\n"
"}\n"
"\n"
"QLineEdit, QTextEdit, QDateTimeEdit {\n"
"    border: 1px solid #edf4fa;\n"
"    border-radius: 8px;\n"
"    padding: 4px;\n"
"    font-family: \"Poppins\", sans-serif;\n"
"    font-weight: normal;\n"
"    font-size: 10pt;\n"
"    background-color: #edf4fa;\n"
"    color: #000000;\n"
"}\n"
"\n"
"QLineEdit:focus, QTextEdit:focus, QDateTimeEdit:focus {\n"
"    border: none;\n"
"    background-color: #bfd5ff;\n"
"}\n"
"\n"
"QDateTimeEdit::down-arrow {\n"
"    image: url(:/icons/icons/chevron-down_black.svg);\n"
"    width: 10px;\n"
"    height: 10px;\n"
"}\n"
"\n"
"QDateTimeEdit::up-arrow {\n"
"    image: url(:/icons/icons/chevron-up_black.svg);\n"
"    width: 10px;\n"
"    height: 10px;\n"
"}\n"
"\n"
"Line {\n"
"    background-color: #92979d;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #2b70ff;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    color: #FFFFFF;\n"
"    text-align: center;\n"
"    font-family: \"Poppins\", sans-serif;\n"
"    font-size: 10pt;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"#addproject_label{\n"
"    color: #2b70ff;\n"
"    font-size: 20pt;\n"
"}\n"
"")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(addproject_dialog)
        self.verticalLayout_6.setContentsMargins(15, 15, 15, 15)
        self.verticalLayout_6.setSpacing(10)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.project_info = QtWidgets.QFrame(parent=addproject_dialog)
        self.project_info.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.project_info.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.project_info.setObjectName("project_info")
        self.gridLayout = QtWidgets.QGridLayout(self.project_info)
        self.gridLayout.setObjectName("gridLayout")
        self.addproject_label = QtWidgets.QLabel(parent=self.project_info)
        self.addproject_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.addproject_label.setObjectName("addproject_label")
        self.gridLayout.addWidget(self.addproject_label, 0, 0, 1, 2)
        self.project_name_frame = QtWidgets.QFrame(parent=self.project_info)
        self.project_name_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.project_name_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.project_name_frame.setObjectName("project_name_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.project_name_frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.project_name = QtWidgets.QLabel(parent=self.project_name_frame)
        self.project_name.setObjectName("project_name")
        self.verticalLayout.addWidget(self.project_name)
        self.project_name_info = QtWidgets.QLineEdit(parent=self.project_name_frame)
        self.project_name_info.setText("")
        self.project_name_info.setObjectName("project_name_info")
        self.verticalLayout.addWidget(self.project_name_info)
        self.gridLayout.addWidget(self.project_name_frame, 1, 0, 1, 1)
        self.project_id_frame = QtWidgets.QFrame(parent=self.project_info)
        self.project_id_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.project_id_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.project_id_frame.setObjectName("project_id_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.project_id_frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.project_id = QtWidgets.QLabel(parent=self.project_id_frame)
        self.project_id.setObjectName("project_id")
        self.verticalLayout_2.addWidget(self.project_id)
        self.project_id_info = QtWidgets.QLineEdit(parent=self.project_id_frame)
        self.project_id_info.setObjectName("project_id_info")
        self.verticalLayout_2.addWidget(self.project_id_info)
        self.gridLayout.addWidget(self.project_id_frame, 1, 1, 1, 1)
        self.project_shortDescrip_frame = QtWidgets.QFrame(parent=self.project_info)
        self.project_shortDescrip_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.project_shortDescrip_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.project_shortDescrip_frame.setObjectName("project_shortDescrip_frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.project_shortDescrip_frame)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.project_shortDescrip = QtWidgets.QLabel(parent=self.project_shortDescrip_frame)
        self.project_shortDescrip.setObjectName("project_shortDescrip")
        self.verticalLayout_3.addWidget(self.project_shortDescrip)
        self.project_shortDescrip_info = QtWidgets.QTextEdit(parent=self.project_shortDescrip_frame)
        self.project_shortDescrip_info.setObjectName("project_shortDescrip_info")
        self.verticalLayout_3.addWidget(self.project_shortDescrip_info)
        self.gridLayout.addWidget(self.project_shortDescrip_frame, 2, 0, 1, 2)
        self.project_startDate_frame = QtWidgets.QFrame(parent=self.project_info)
        self.project_startDate_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.project_startDate_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.project_startDate_frame.setObjectName("project_startDate_frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.project_startDate_frame)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.project_startDate = QtWidgets.QLabel(parent=self.project_startDate_frame)
        self.project_startDate.setObjectName("project_startDate")
        self.verticalLayout_4.addWidget(self.project_startDate)
        self.project_startDate_info = QtWidgets.QDateTimeEdit(parent=self.project_startDate_frame)
        self.project_startDate_info.setObjectName("project_startDate_info")
        self.verticalLayout_4.addWidget(self.project_startDate_info)
        self.gridLayout.addWidget(self.project_startDate_frame, 3, 0, 1, 1)
        self.project_endDate_frame = QtWidgets.QFrame(parent=self.project_info)
        self.project_endDate_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.project_endDate_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.project_endDate_frame.setObjectName("project_endDate_frame")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.project_endDate_frame)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.project_endDate = QtWidgets.QLabel(parent=self.project_endDate_frame)
        self.project_endDate.setObjectName("project_endDate")
        self.verticalLayout_5.addWidget(self.project_endDate)
        self.project_endDate_info = QtWidgets.QDateTimeEdit(parent=self.project_endDate_frame)
        self.project_endDate_info.setObjectName("project_endDate_info")
        self.verticalLayout_5.addWidget(self.project_endDate_info)
        self.gridLayout.addWidget(self.project_endDate_frame, 3, 1, 1, 1)
        self.verticalLayout_6.addWidget(self.project_info)
        self.hline = QtWidgets.QFrame(parent=addproject_dialog)
        self.hline.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.hline.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.hline.setObjectName("hline")
        self.verticalLayout_6.addWidget(self.hline)
        self.frame = QtWidgets.QFrame(parent=addproject_dialog)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.project_save_button = QtWidgets.QPushButton(parent=self.frame)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/save.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.project_save_button.setIcon(icon)
        self.project_save_button.setObjectName("project_save_button")
        self.horizontalLayout.addWidget(self.project_save_button)
        self.project_clear_button = QtWidgets.QPushButton(parent=self.frame)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/delete.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.project_clear_button.setIcon(icon1)
        self.project_clear_button.setObjectName("project_clear_button")
        self.horizontalLayout.addWidget(self.project_clear_button)
        self.project_cancel_button = QtWidgets.QPushButton(parent=self.frame)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/x-square.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.project_cancel_button.setIcon(icon2)
        self.project_cancel_button.setObjectName("project_cancel_button")
        self.horizontalLayout.addWidget(self.project_cancel_button)
        self.verticalLayout_6.addWidget(self.frame)

        self.retranslateUi(addproject_dialog)
        QtCore.QMetaObject.connectSlotsByName(addproject_dialog)

    def retranslateUi(self, addproject_dialog):
        _translate = QtCore.QCoreApplication.translate
        addproject_dialog.setWindowTitle(_translate("addproject_dialog", "Dialog"))
        self.addproject_label.setText(_translate("addproject_dialog", "PROJECT"))
        self.project_name.setText(_translate("addproject_dialog", "PROJECT NAME"))
        self.project_name_info.setPlaceholderText(_translate("addproject_dialog", "Enter project name"))
        self.project_id.setText(_translate("addproject_dialog", "PROJECT ID"))
        self.project_id_info.setPlaceholderText(_translate("addproject_dialog", "NNNN-NNNN"))
        self.project_shortDescrip.setText(_translate("addproject_dialog", "DESCRIPTION"))
        self.project_shortDescrip_info.setPlaceholderText(_translate("addproject_dialog", "Enter a short description"))
        self.project_startDate.setText(_translate("addproject_dialog", "START DATE"))
        self.project_endDate.setText(_translate("addproject_dialog", "END DATE"))
        self.project_save_button.setText(_translate("addproject_dialog", "Save"))
        self.project_clear_button.setText(_translate("addproject_dialog", "Clear"))
        self.project_cancel_button.setText(_translate("addproject_dialog", "Cancel"))
