# Form implementation generated from reading ui file 'addtask_interface.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QGraphicsDropShadowEffect
from PyQt6.QtGui import QColor

class Ui_addtask_dialog(object):
    def setupUi(self, addtask_dialog):
        addtask_dialog.setObjectName("addtask_dialog")
        addtask_dialog.resize(616, 543)
        addtask_dialog.setStyleSheet("QDialog{\n"
"    background-color: #edf4fa;\n"
"}\n"
"\n"
"QFrame {\n"
"    background-color: #FFFFFF;\n"
"    border: 1px solid #FFFFFF;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QLabel    {\n"
"    font-family: \"Poppins\", sans-serif;\n"
"    font-size: 15px;\n"
"    color: #000000;\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"#task_project, #task_status, #task_name, #task_id, #task_shortDescrip, #task_dueDate, #task_dateAccomplished{\n"
"    font-weight: bold;\n"
"    font-size: 8pt;\n"
"    color: #92979d;\n"
"}\n"
"\n"
"#addtask_label {\n"
"    font-weight: bold;\n"
"    font-size: 20pt;\n"
"    color: #fe9137;\n"
"}\n"
"\n"
"QLineEdit, QTextEdit, QDateTimeEdit, QComboBox {\n"
"    border: 1px solid #edf4fa;\n"
"    border-radius: 8px;\n"
"    padding: 4px;\n"
"    font-family: \"Poppins\", sans-serif;\n"
"    font-weight: normal;\n"
"    font-size: 10pt;\n"
"    background-color: #edf4fa;\n"
"    color: #000000;\n"
"}\n"
"\n"
"QLineEdit:focus, QTextEdit:focus, QDateTimeEdit:focus, QComboBox:focus {\n"
"    border: none;\n"
"    background-color: #ffdcbf;\n"
"}\n"
"\n"
"QDateTimeEdit::down-arrow {\n"
"    image: url(icons/chevron-down_black.svg);\n"
"    width: 10px;\n"
"    height: 10px;\n"
"}\n"
"\n"
"QDateTimeEdit::up-arrow {\n"
"    image: url(icons/chevron-up_black.svg);\n"
"    width: 10px;\n"
"    height: 10px;\n"
"}\n"
"QPushButton {\n"
"    background-color: #fe9137;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    color: #FFFFFF;\n"
"    text-align: center;\n"
"    font-family: \"Poppins\", sans-serif;\n"
"    font-size: 15px;\n"
"    padding: 8px;\n"
"}\n"
"\n"
"#task_save_button, #task_clear_button, #task_cancel_button {\n"
"    font-size: 10pt;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"Line {\n"
"    background-color: #92979d;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: url(icons/chevron-down_black.svg);\n"
"    width: 20px;\n"
"    height: 20px;\n"
"}\n"
"\n"
"#addtask_label{\n"
"    color: #fe9137;\n"
"    font-size: 20pt;\n"
"}")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(addtask_dialog)
        self.verticalLayout_6.setContentsMargins(15, 15, 15, 15)
        self.verticalLayout_6.setSpacing(10)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.task_info = QtWidgets.QFrame(parent=addtask_dialog)
        self.task_info.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.task_info.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.task_info.setObjectName("task_info")
        self.gridLayout = QtWidgets.QGridLayout(self.task_info)
        self.gridLayout.setObjectName("gridLayout")
        self.task_dateAccomplished = QtWidgets.QLabel(parent=self.task_info)
        self.task_dateAccomplished.setObjectName("task_dateAccomplished")
        self.gridLayout.addWidget(self.task_dateAccomplished, 4, 1, 1, 1)
        self.task_dateAccomplished_info = QtWidgets.QDateTimeEdit(parent=self.task_info)
        self.task_dateAccomplished_info.setObjectName("task_dateAccomplished_info")
        # Set minimum datetime
        min_datetime = QtCore.QDateTime.fromString("2000-01-01T00:00:00", QtCore.Qt.DateFormat.ISODate)
        if not min_datetime.isValid():
            min_datetime = QtCore.QDateTime(2000, 1, 1, 0, 0)

        self.task_dateAccomplished_info.setMinimumDateTime(min_datetime)

        # Set special text to show when date = minimum date
        self.task_dateAccomplished_info.setSpecialValueText("No date set")

        # Initialize with minimum datetime so "No date set" is shown
        self.task_dateAccomplished_info.setDateTime(min_datetime)
        self.gridLayout.addWidget(self.task_dateAccomplished_info, 5, 1, 1, 1)
        self.task_dueDate = QtWidgets.QLabel(parent=self.task_info)
        self.task_dueDate.setObjectName("task_dueDate")
        self.gridLayout.addWidget(self.task_dueDate, 4, 0, 1, 1)
        self.task_dueDate_info = QtWidgets.QDateTimeEdit(parent=self.task_info)
        self.task_dueDate_info.setObjectName("task_dueDate_info")
        self.gridLayout.addWidget(self.task_dueDate_info, 5, 0, 1, 1)
        self.task_status_frame = QtWidgets.QFrame(parent=self.task_info)
        self.task_status_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.task_status_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.task_status_frame.setObjectName("task_status_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.task_status_frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.task_status = QtWidgets.QLabel(parent=self.task_status_frame)
        self.task_status.setObjectName("task_status")
        self.verticalLayout_2.addWidget(self.task_status)
        self.task_status_info = QtWidgets.QComboBox(parent=self.task_status_frame)
        self.task_status_info.setObjectName("task_status_info")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/check-circle_orange.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.task_status_info.addItem(icon, "")
        self.task_status_info.addItem("")
        self.task_status_info.addItem("")
        self.task_status_info.addItem("")
        self.task_status_info.addItem("")
        self.verticalLayout_2.addWidget(self.task_status_info)
        self.gridLayout.addWidget(self.task_status_frame, 1, 1, 1, 1)
        self.task_project_frame = QtWidgets.QFrame(parent=self.task_info)
        self.task_project_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.task_project_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.task_project_frame.setObjectName("task_project_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.task_project_frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.task_project = QtWidgets.QLabel(parent=self.task_project_frame)
        self.task_project.setObjectName("task_project")
        self.verticalLayout.addWidget(self.task_project)
        self.task_project_info = QtWidgets.QComboBox(parent=self.task_project_frame)
        self.task_project_info.setObjectName("task_project_info")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/folder_orange.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.task_project_info.addItem(icon1, "")
        self.verticalLayout.addWidget(self.task_project_info)
        self.gridLayout.addWidget(self.task_project_frame, 1, 0, 1, 1)
        self.task_shortDescrip_frame = QtWidgets.QFrame(parent=self.task_info)
        self.task_shortDescrip_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.task_shortDescrip_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.task_shortDescrip_frame.setObjectName("task_shortDescrip_frame")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.task_shortDescrip_frame)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.task_shortDescrip = QtWidgets.QLabel(parent=self.task_shortDescrip_frame)
        self.task_shortDescrip.setObjectName("task_shortDescrip")
        self.verticalLayout_5.addWidget(self.task_shortDescrip)
        self.task_shortDescrip_info = QtWidgets.QTextEdit(parent=self.task_shortDescrip_frame)
        self.task_shortDescrip_info.setObjectName("task_shortDescrip_info")
        self.verticalLayout_5.addWidget(self.task_shortDescrip_info)
        self.gridLayout.addWidget(self.task_shortDescrip_frame, 3, 0, 1, 2)
        self.task_id_frame = QtWidgets.QFrame(parent=self.task_info)
        self.task_id_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.task_id_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.task_id_frame.setObjectName("task_id_frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.task_id_frame)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.task_id = QtWidgets.QLabel(parent=self.task_id_frame)
        self.task_id.setObjectName("task_id")
        self.verticalLayout_4.addWidget(self.task_id)
        self.task_id_info = QtWidgets.QLineEdit(parent=self.task_id_frame)
        self.task_id_info.setText("")
        self.task_id_info.setObjectName("task_id_info")
        self.verticalLayout_4.addWidget(self.task_id_info)
        self.gridLayout.addWidget(self.task_id_frame, 2, 1, 1, 1)
        self.task_name_frame = QtWidgets.QFrame(parent=self.task_info)
        self.task_name_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.task_name_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.task_name_frame.setObjectName("task_name_frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.task_name_frame)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.task_name = QtWidgets.QLabel(parent=self.task_name_frame)
        self.task_name.setObjectName("task_name")
        self.verticalLayout_3.addWidget(self.task_name)
        self.task_name_info = QtWidgets.QLineEdit(parent=self.task_name_frame)
        self.task_name_info.setText("")
        self.task_name_info.setObjectName("task_name_info")
        self.verticalLayout_3.addWidget(self.task_name_info)
        self.gridLayout.addWidget(self.task_name_frame, 2, 0, 1, 1)
        self.addtask_label = QtWidgets.QLabel(parent=self.task_info)
        self.addtask_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.addtask_label.setObjectName("addtask_label")
        self.gridLayout.addWidget(self.addtask_label, 0, 0, 1, 2)
        self.verticalLayout_6.addWidget(self.task_info)
        self.hline = QtWidgets.QFrame(parent=addtask_dialog)
        self.hline.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.hline.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.hline.setObjectName("hline")
        self.verticalLayout_6.addWidget(self.hline)
        self.frame = QtWidgets.QFrame(parent=addtask_dialog)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.task_save_button = QtWidgets.QPushButton(parent=self.frame)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/save.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.task_save_button.setIcon(icon2)
        self.task_save_button.setObjectName("task_save_button")
        self.task_save_button.setMinimumHeight(30)
        self.horizontalLayout.addWidget(self.task_save_button)
        self.task_clear_button = QtWidgets.QPushButton(parent=self.frame)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/delete.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.task_clear_button.setIcon(icon3)
        self.task_clear_button.setObjectName("task_clear_button")
        self.task_clear_button.setMinimumHeight(30)
        self.horizontalLayout.addWidget(self.task_clear_button)
        self.task_cancel_button = QtWidgets.QPushButton(parent=self.frame)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/x-square.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.task_cancel_button.setIcon(icon4)
        self.task_cancel_button.setObjectName("task_cancel_button")
        self.task_cancel_button.setMinimumHeight(30)
        self.horizontalLayout.addWidget(self.task_cancel_button)
        self.verticalLayout_6.addWidget(self.frame)

        frames = [self.task_info, self.frame]
        for frame in frames:
            shadow = QGraphicsDropShadowEffect(frame)
            shadow.setBlurRadius(20)
            shadow.setOffset(0, 0)
            shadow.setColor(QColor(0, 0, 0, 80))
            frame.setGraphicsEffect(shadow)

        self.retranslateUi(addtask_dialog)
        QtCore.QMetaObject.connectSlotsByName(addtask_dialog)

        self.task_project_info.setStyleSheet("""
            QComboBox {
                color: #000000;
            }
            QComboBox QAbstractItemView {
                color: #000000;
            }
        """)

        self.task_status_info.setStyleSheet("""
            QComboBox {
                color: #000000;
            }
            QComboBox QAbstractItemView {
                color: #000000;
            }
        """)

    def retranslateUi(self, addtask_dialog):
        _translate = QtCore.QCoreApplication.translate
        addtask_dialog.setWindowTitle(_translate("addtask_dialog", "Dialog"))
        self.task_dateAccomplished.setText(_translate("addtask_dialog", "DATE ACCOMPLISHED"))
        self.task_dueDate.setText(_translate("addtask_dialog", "DUE DATE"))
        self.task_status.setText(_translate("addtask_dialog", "STATUS"))
        self.task_status_info.setItemText(0, _translate("addtask_dialog", "Select status"))
        self.task_status_info.setItemText(1, _translate("addtask_dialog", "Unassigned"))
        self.task_status_info.setItemText(2, _translate("addtask_dialog", "Pending"))
        self.task_status_info.setItemText(3, _translate("addtask_dialog", "In Progress"))
        self.task_status_info.setItemText(4, _translate("addtask_dialog", "Completed"))
        self.task_project.setText(_translate("addtask_dialog", "PROJECT"))
        self.task_project_info.setItemText(0, _translate("addtask_dialog", "Select a project"))
        self.task_shortDescrip.setText(_translate("addtask_dialog", "DESCRIPTION"))
        self.task_shortDescrip_info.setPlaceholderText(_translate("addtask_dialog", "Enter a short description"))
        self.task_id.setText(_translate("addtask_dialog", "TASK ID"))
        self.task_id_info.setPlaceholderText(_translate("addtask_dialog", "NNNN-NNNN"))
        self.task_name.setText(_translate("addtask_dialog", "TASK NAME"))
        self.task_name_info.setPlaceholderText(_translate("addtask_dialog", "Enter task name"))
        self.addtask_label.setText(_translate("addtask_dialog", "TASK"))
        self.task_save_button.setText(_translate("addtask_dialog", "Save"))
        self.task_clear_button.setText(_translate("addtask_dialog", "Clear"))
        self.task_cancel_button.setText(_translate("addtask_dialog", "Cancel"))
