# Form implementation generated from reading ui file 'main_interface.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QGraphicsDropShadowEffect
from PyQt6.QtGui import QColor
from models.project import loadProjects, loadOnGoingProjects
from models.task import loadTasks
from utils.clickableLabel import ClickableLabel


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1167, 733)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("QMainWindow {\n"
"    background-color: #edf4fa;\n"
"}\n"
"\n"
"QWidget{\n"
"    background-color: #edf4fa; \n"
"}\n"
"\n"
"QFrame {\n"
"    background-color: #edf4fa;\n"
"    border: none;\n"
"}\n"
"\n"
"QLabel {\n"
"    font-family: \"Poppins\", sans-serif;\n"
"    font-size: 15px;\n"
"    background-color: transparent;\n"
"    color: #000000;\n"
"}\n"
"\n"
"""
#topbar, #planado, #menu_board, #frame, #menu_buttons,
#home_bar, #view_projects, #projects_bar, #projects_container,
#project_details, #tasks_bar, #tasks_container, #task_details,
#members_bar, #members_table_frame, #project_details_frame, #task_details_frame, #projects_total, #tasks_total, #members_total {
    background-color: #FFFFFF;
    border: 1px solid #FFFFFF;
    border-radius: 8px;
}
"""
"\n"
"#planado_title, #view_projects_label {\n"
"    font-family: \"Poppins\", sans-serif;\n"
"    font-weight: bold;\n"
"    font-size: 20pt;\n"
"    color: #7f00ff;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: url(icons/chevron-down_black.svg);\n"
"    width: 20px;\n"
"    height: 20px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #7f00ff;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    color: #FFFFFF;\n"
"    text-align: center;\n"
"    padding: 8px;\n"
"    font-family: \"Poppins\", sans-serif;\n"
"    font-size: 15px;\n"
"}\n"
"\n"
"#home_button, #projects_button, #tasks_button, #members_button, #planado_icon {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    color: black;\n"
"    text-align: left;\n"
"    padding: 8px 12px;\n"
"    font-family: \"Poppins\", sans-serif;\n"
"    font-size: 15px;\n"
"}\n"
"\n"
"/* calendar stylesheet */\n" #calendar stylesheet

"\n"
"QScrollBar:vertical {\n"
"    background-color: #878787;\n"
"    width: 12px;\n"
"    margin: 0px;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: #edf4fa;\n"
"    min-height: 20px;\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QTableWidget {\n"
"    border: 1px solid #FFFFFF;\n"
"    border-radius: 8px;\n"
"    gridline-color: transparent;\n"
"    font-family: \"Poppins\", sans-serif;\n"
"    font-weight: normal;\n"
"    font-size: 13px;\n"
"    alternate-background-color: #aef2e0;\n"
"    background-color: #FFFFFF;\n"
"    selection-background-color: #01c28e;\n"
"    selection-color: #FFFFFF;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #01c28e;\n"
"    color: #FFFFFF;\n"
"    font-family: \"Poppins\", sans-serif;\n"
"    font-weight: bold;\n"
"    font-size: 15px;\n"
"    border: 1px solid #014d38;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    color: black;\n"
"    padding: 5px;\n"
"    font-family: \"Poppins\", sans-serif;\n"
"    font-weight: bold;\n"
"    font-size: 15px;\n"
"}\n"
"\n"
"QTableWidget::item:hover {\n"
"    background-color: #01c28e;\n"
"    color: #FFFFFF;\n"
"}\n"
"\n"
"/* home search stylesheet */\n"
"\n"
"#home_search, #projects_search, #tasks_search, #members_search {\n"
"    background-color: #edf4fa;\n"
"    border: 1px solid #edf4fa;\n"
"    border-radius: 8px;\n"
"    font-family: \"Poppins\", sans-serif;\n"
"    font-weight: normal;\n"
"    font-size: 15px;\n"
"    background-image: url(icons/search_gray.svg);\n"
"    background-repeat: no-repeat;\n"
"    background-position: left center;\n"
"    padding-left: 28px;\n"
"    color: #000000;\n"
"}\n"
"\n"
"#home_searchby, #projects_searchby, #projects_sortby, #tasks_searchby, #tasks_sortby, #members_searchby {\n"
"    background-color: #edf4fa;\n"
"    border: 1px solid #edf4fa;\n"
"    border-radius: 8px;\n"
"    padding: 5px 15px 5px 5px; \n"
"    font-family: \"Poppins\", sans-serif;\n"
"    font-weight: normal;\n"
"    font-size: 15px;\n"
"    color: #000000;\n"
"}\n"
"\n"
"""
#home_searchby QAbstractItemView, 
#projects_searchby QAbstractItemView, 
#projects_sortby QAbstractItemView, 
#tasks_searchby QAbstractItemView, 
#tasks_sortby QAbstractItemView, 
#members_searchby QAbstractItemView, 
#members_sortby QAbstractItemView {
    background-color: #edf4fa;  /* Match the combo box bg */  
    border-radius: 8px;
    padding: 3px;
    font-family: "Poppins", sans-serif;
    font-size: 15px;
    margin-top: 5px;  /* Spacing from the combo box */
}

/* Default item style (applies always) */
#home_searchby QAbstractItemView::item, 
#projects_searchby QAbstractItemView::item, 
#projects_sortby QAbstractItemView::item, 
#tasks_searchby QAbstractItemView::item, 
#tasks_sortby QAbstractItemView::item, 
#members_searchby QAbstractItemView::item, 
#members_sortby QAbstractItemView::item {
    background-color: #edf4fa;  /* Same as dropdown */
    color: black;
    height: 25px;
    
}

/* Hover state (optional - can remove if you want no hover effect) */
#home_searchby QAbstractItemView::item:hover, 
#projects_searchby QAbstractItemView::item:hover, 
#projects_sortby QAbstractItemView::item:hover, 
#tasks_searchby QAbstractItemView::item:hover, 
#tasks_sortby QAbstractItemView::item:hover, 
#members_searchby QAbstractItemView::item:hover, 
#members_sortby QAbstractItemView::item:hover {
    background-color: #d0e3f7;  /* Slightly darker on hover */
}

/* Selected item state (keep visible selection) */
#home_searchby QAbstractItemView::item:selected, 
#projects_searchby QAbstractItemView::item:selected, 
#projects_sortby QAbstractItemView::item:selected, 
#tasks_searchby QAbstractItemView::item:selected, 
#tasks_sortby QAbstractItemView::item:selected, 
#members_searchby QAbstractItemView::item:selected, 
#members_sortby QAbstractItemView::item:selected {
    background-color: #a8c9eb;  /* Even darker for selection */
    color: black;
}
"""
"/* menu buttons stylesheet */\n"
"\n"
"#home_button:hover, #projects_button:hover, #tasks_button:hover, #members_button:hover {\n"
"    background-color: #d9ebfa;\n"
"}\n"
"\n"
"/* total header */\n"
"\n"
"#total_frame {\n"
"    background-color: #edf4fa;\n"
"}\n"
"\n"
"#projects_total {\n"
"    background-color: #2b70ff;\n"
"}\n"
"\n"
"#tasks_total {\n"
"    background-color: #fe9137;\n"
"}\n"
"\n"
"#members_total {\n"
"    background-color: #01c28e;\n"
"}\n"
"\n"
"#projects_total_label, #tasks_total_label, #members_total_label {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    font-family: \"Poppins\", sans-serif;\n"
"    font-weight: bold;\n"
"    font-size: 15pt;\n"
"    color: #FFFFFF;\n"
"}\n"
"\n"
"#projects_total_label_2, #tasks_total_label_2, #members_total_label_2 {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    font-family: \"Poppins\", sans-serif;\n"
"    font-weight: bold;\n"
"    font-size: 30pt;\n"
"    color: rgba(255, 255, 255, 80);\n"
"}\n"
"\n"
"#projects_total_design, #tasks_total_design, #members_total_design {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"#projects_total_count, #tasks_total_count, #members_total_count {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    font-family: \"Poppins\", sans-serif;\n"
"    font-weight: bold;\n"
"    font-size: 50pt;\n"
"    color: #FFFFFF;\n"
"}\n"
"\n"
"#view_projects_label{\n"
"    font-size: 15pt;\n"
"    color: #7f00ff;\n"
"}\n"
"\n"
"#addproject_button {\n"
"    background-color: #2b70ff;\n"
"    border: 1px solid #2b70ff;\n"
"    font-family: \"Poppins\", sans-serif;\n"
"    font-weight: bold;\n"
"    font-size: 15px;\n"
"    color: #FFFFFF;\n"
"    text-align: center;\n"
"}\n"
"\n"
"#project_details_label {\n"
"    font-family: \"Poppins\", sans-serif;\n"
"    font-weight: bold;\n"
"    font-size: 12pt;\n"
"    color: #2b70ff;\n"
"}\n"
"\n"
"#task_details_label {\n"
"    font-family: \"Poppins\", sans-serif;\n"
"    font-weight: bold;\n"
"    font-size: 12pt;\n"
"    color: #fe9137;\n"
"}\n"
"\n"
"#project_name, #project_id, #project_startDate, #project_endDate, #project_totalMembers, #project_totalTasks, #task_name, #task_id, #task_project, #task_status, #task_dueDate, #task_totalMembers {\n"
"    font-family: \"Poppins\", sans-serif;\n"
"    font-weight: bold;\n"
"    font-size: 15px;\n"
"    color: #000000;\n"
"}\n"
"\n"
"#project_name_info,#project_id_info, #project_startDate_info, #project_endDate_info, #project_totalMembers_info, #project_totalTasks_info, #task_name_info, #task_id_info, #task_project_info, #task_status_info, #task_dueDate_info, #task_totalMembers_info {\n"
"    font-family: \"Poppins\", sans-serif;\n"
"    font-weight: normal;\n"
"    font-size: 14px;\n"
"    color: #000000;\n"
"}\n"
"\n"
"#project_name, #task_project {\n"
"    background-image: url(icons/folder_black.svg);\n"
"    background-repeat: no-repeat;\n"
"    background-position: left center;\n"
"    padding-left: 30px; /* Space for the icon */\n"
"}\n"
"\n"
"#project_id, #task_id {\n"
"    background-image: url(icons/key_black.svg);\n"
"    background-repeat: no-repeat;\n"
"    background-position: left center;\n"
"    padding-left: 30px; /* Space for the icon */\n"
"}\n"
"\n"
"#project_startDate, #project_endDate, #task_dueDate {\n"
"    background-image: url(icons/calendar_black.svg);\n"
"    background-repeat: no-repeat;\n"
"    background-position: left center;\n"
"    padding-left: 30px; /* Space for the icon */\n"
"}\n"
"\n"
"#project_totalMembers, #task_totalMembers  {\n"
"    background-image: url(icons/users_black.svg);\n"
"    background-repeat: no-repeat;\n"
"    background-position: left center;\n"
"    padding-left: 30px; /* Space for the icon */\n"
"}\n"
"\n"
"#project_totalTasks, #task_name {\n"
"    background-image: url(icons/clipboard_black.svg);\n"
"    background-repeat: no-repeat;\n"
"    background-position: left center;\n"
"    padding-left: 30px; /* Space for the icon */\n"
"}\n"
"\n"
"#task_status {\n"
"    background-image: url(icons/circle_black.svg);\n"
"    background-repeat: no-repeat;\n"
"    background-position: left center;\n"
"    padding-left: 30px; /* Space for the icon */\n"
"}\n"
"\n"
"#project_expand_button {\n"
"    background-color: #2b70ff;\n"
"    border: 1px solid #2b70ff;\n"
"    font-family: \"Poppins\", sans-serif;\n"
"    font-weight: bold;\n"
"    font-size: 15px;\n"
"    color: #FFFFFF;\n"
"    text-align: center;\n"
"}\n"
"\n"
"#addtask_button {\n"
"    background-color: #fe9137;\n"
"    border: 1px solid #fe9137;\n"
"    font-family: \"Poppins\", sans-serif;\n"
"    font-weight: bold;\n"
"    font-size: 15px;\n"
"    color: #FFFFFF;\n"
"    text-align: center;\n"
"}\n"
"\n"
"#task_expand_button {\n"
"    background-color: #fe9137;\n"
"    border: 1px solid #fe9137;\n"
"    font-family: \"Poppins\", sans-serif;\n"
"    font-weight: bold;\n"
"    font-size: 15px;\n"
"    color: #FFFFFF;\n"
"    text-align: center;\n"
"}\n"
"\n"
"#addmember_button {\n"
"    background-color: #01c28e;\n"
"    border: 1px solid #01c28e;\n"
"    font-family: \"Poppins\", sans-serif;\n"
"    font-weight: bold;\n"
"    font-size: 15px;\n"
"    color: #FFFFFF;\n"
"    text-align: center;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.topbar = QtWidgets.QFrame(parent=self.centralwidget)
        self.topbar.setMinimumSize(QtCore.QSize(1111, 66))
        self.topbar.setMaximumSize(QtCore.QSize(16777215, 66))
        self.topbar.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.topbar.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.topbar.setObjectName("topbar")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.topbar)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.planado = QtWidgets.QFrame(parent=self.topbar)
        self.planado.setMinimumSize(QtCore.QSize(191, 44))
        self.planado.setMaximumSize(QtCore.QSize(191, 44))
        self.planado.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.planado.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.planado.setObjectName("planado")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.planado)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.planado_icon = QtWidgets.QPushButton(parent=self.planado)
        self.planado_icon.setMaximumSize(QtCore.QSize(30, 16777215))
        self.planado_icon.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/briefcase.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.planado_icon.setIcon(icon)
        self.planado_icon.setObjectName("planado_icon")
        self.horizontalLayout.addWidget(self.planado_icon)
        self.planado_title = QtWidgets.QLabel(parent=self.planado)
        self.planado_title.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.planado_title.setObjectName("planado_title")
        self.horizontalLayout.addWidget(self.planado_title)
        self.horizontalLayout_3.addWidget(self.planado)
        spacerItem = QtWidgets.QSpacerItem(920, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.gridLayout.addWidget(self.topbar, 0, 0, 1, 2)
        self.menu_board = QtWidgets.QFrame(parent=self.centralwidget)
        self.menu_board.setMinimumSize(QtCore.QSize(171, 0))
        self.menu_board.setMaximumSize(QtCore.QSize(171, 16777215))
        self.menu_board.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.menu_board.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.menu_board.setObjectName("menu_board")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.menu_board)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.menu_buttons = QtWidgets.QFrame(parent=self.menu_board)
        self.menu_buttons.setMaximumSize(QtCore.QSize(151, 213))
        self.menu_buttons.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.menu_buttons.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.menu_buttons.setObjectName("menu_buttons")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.menu_buttons)
        self.verticalLayout.setObjectName("verticalLayout")
        self.home_button = QtWidgets.QPushButton(parent=self.menu_buttons)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/home_black.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.home_button.setIcon(icon1)
        self.home_button.setObjectName("home_button")
        self.verticalLayout.addWidget(self.home_button)
        self.projects_button = QtWidgets.QPushButton(parent=self.menu_buttons)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/folder_black.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.projects_button.setIcon(icon2)
        self.projects_button.setObjectName("projects_button")
        self.verticalLayout.addWidget(self.projects_button)
        self.tasks_button = QtWidgets.QPushButton(parent=self.menu_buttons)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/clipboard_black.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.tasks_button.setIcon(icon3)
        self.tasks_button.setObjectName("tasks_button")
        self.verticalLayout.addWidget(self.tasks_button)
        self.members_button = QtWidgets.QPushButton(parent=self.menu_buttons)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/users_black.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.members_button.setIcon(icon4)
        self.members_button.setObjectName("members_button")
        self.verticalLayout.addWidget(self.members_button)
        self.verticalLayout_2.addWidget(self.menu_buttons)
        self.frame = QtWidgets.QFrame(parent=self.menu_board)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2.addWidget(self.frame)
        self.gridLayout.addWidget(self.menu_board, 1, 0, 1, 1)
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.home_page = QtWidgets.QWidget()
        self.home_page.setObjectName("home_page")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.home_page)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(10)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.total_frame = QtWidgets.QFrame(parent=self.home_page)
        self.total_frame.setMinimumSize(QtCore.QSize(0, 131))
        self.total_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.total_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.total_frame.setObjectName("total_frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.total_frame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.total_frame = QtWidgets.QFrame(parent=self.home_page)
        self.total_frame.setMinimumSize(QtCore.QSize(0, 131))
        self.total_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.total_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.total_frame.setObjectName("total_frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.total_frame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.projects_total = QtWidgets.QFrame(parent=self.total_frame)
        self.projects_total.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.projects_total.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.projects_total.setObjectName("projects_total")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.projects_total)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.projects_total_design = QtWidgets.QFrame(parent=self.projects_total)
        self.projects_total_design.setMinimumSize(QtCore.QSize(270, 0))
        self.projects_total_design.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.projects_total_design.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.projects_total_design.setObjectName("projects_total_design")
        self.projects_total_label_2 = QtWidgets.QLabel(parent=self.projects_total_design)
        self.projects_total_label_2.setGeometry(QtCore.QRect(20, 20, 221, 61))
        self.projects_total_label_2.setObjectName("projects_total_label_2")
        self.projects_total_label = QtWidgets.QLabel(parent=self.projects_total_design)
        self.projects_total_label.setGeometry(QtCore.QRect(0, 10, 171, 41))
        self.projects_total_label.setObjectName("projects_total_label")
        self.gridLayout_6.addWidget(self.projects_total_design, 0, 0, 2, 2)
        self.frame_3 = QtWidgets.QFrame(parent=self.projects_total)
        self.frame_3.setStyleSheet("background-color: transparent;\n"
"border: none;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_6.addWidget(self.frame_3, 0, 2, 1, 1)
        self.projects_total_count = ClickableLabel(parent=self.projects_total)
        self.projects_total_count.setMinimumSize(QtCore.QSize(0, 100))
        self.projects_total_count.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTop|QtCore.Qt.AlignmentFlag.AlignTrailing)
        self.projects_total_count.setObjectName("projects_total_count")
        self.gridLayout_6.addWidget(self.projects_total_count, 1, 1, 1, 2)
        self.frame_2 = QtWidgets.QFrame(parent=self.projects_total)
        self.frame_2.setStyleSheet("background-color: transparent;\n"
"border: none;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_6.addWidget(self.frame_2, 2, 0, 1, 2)
        self.horizontalLayout_2.addWidget(self.projects_total)
        self.tasks_total = QtWidgets.QFrame(parent=self.total_frame)
        self.tasks_total.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.tasks_total.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.tasks_total.setObjectName("tasks_total")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tasks_total)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.tasks_total_design = QtWidgets.QFrame(parent=self.tasks_total)
        self.tasks_total_design.setMinimumSize(QtCore.QSize(270, 0))
        self.tasks_total_design.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.tasks_total_design.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.tasks_total_design.setObjectName("tasks_total_design")
        self.tasks_total_label_2 = QtWidgets.QLabel(parent=self.tasks_total_design)
        self.tasks_total_label_2.setGeometry(QtCore.QRect(20, 20, 221, 61))
        self.tasks_total_label_2.setObjectName("tasks_total_label_2")
        self.tasks_total_label = QtWidgets.QLabel(parent=self.tasks_total_design)
        self.tasks_total_label.setGeometry(QtCore.QRect(0, 10, 171, 41))
        self.tasks_total_label.setObjectName("tasks_total_label")
        self.gridLayout_7.addWidget(self.tasks_total_design, 0, 0, 2, 2)
        self.frame_5 = QtWidgets.QFrame(parent=self.tasks_total)
        self.frame_5.setStyleSheet("background-color: transparent;\n"
"border: none;")
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_7.addWidget(self.frame_5, 0, 2, 1, 1)
        self.tasks_total_count = ClickableLabel(parent=self.tasks_total)
        self.tasks_total_count.setMinimumSize(QtCore.QSize(0, 100))
        self.tasks_total_count.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTop|QtCore.Qt.AlignmentFlag.AlignTrailing)
        self.tasks_total_count.setObjectName("tasks_total_count")
        self.gridLayout_7.addWidget(self.tasks_total_count, 1, 1, 1, 2)
        self.frame_4 = QtWidgets.QFrame(parent=self.tasks_total)
        self.frame_4.setStyleSheet("background-color: transparent;\n"
"border: none;")
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_7.addWidget(self.frame_4, 2, 0, 1, 2)
        self.horizontalLayout_2.addWidget(self.tasks_total)
        self.members_total = QtWidgets.QFrame(parent=self.total_frame)
        self.members_total.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.members_total.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.members_total.setObjectName("members_total")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.members_total)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.frame_6 = QtWidgets.QFrame(parent=self.members_total)
        self.frame_6.setStyleSheet("background-color: transparent;\n"
"border: none;")
        self.frame_6.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_6.setObjectName("frame_6")
        self.gridLayout_8.addWidget(self.frame_6, 2, 0, 1, 2)
        self.frame_7 = QtWidgets.QFrame(parent=self.members_total)
        self.frame_7.setStyleSheet("background-color: transparent;\n"
"border: none;")
        self.frame_7.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_7.setObjectName("frame_7")
        self.gridLayout_8.addWidget(self.frame_7, 0, 2, 1, 1)
        self.members_total_design = QtWidgets.QFrame(parent=self.members_total)
        self.members_total_design.setMinimumSize(QtCore.QSize(270, 0))
        self.members_total_design.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.members_total_design.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.members_total_design.setObjectName("members_total_design")
        self.members_total_label_2 = QtWidgets.QLabel(parent=self.members_total_design)
        self.members_total_label_2.setGeometry(QtCore.QRect(20, 20, 261, 61))
        self.members_total_label_2.setObjectName("members_total_label_2")
        self.members_total_label = QtWidgets.QLabel(parent=self.members_total_design)
        self.members_total_label.setGeometry(QtCore.QRect(0, 10, 171, 41))
        self.members_total_label.setObjectName("members_total_label")
        self.gridLayout_8.addWidget(self.members_total_design, 0, 0, 2, 2)
        self.members_total_count = ClickableLabel(parent=self.members_total)
        self.members_total_count.setMinimumSize(QtCore.QSize(0, 100))
        self.members_total_count.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTop|QtCore.Qt.AlignmentFlag.AlignTrailing)
        self.members_total_count.setObjectName("members_total_count")
        self.gridLayout_8.addWidget(self.members_total_count, 1, 2, 1, 1)
        self.horizontalLayout_2.addWidget(self.members_total)
        self.gridLayout_2.addWidget(self.total_frame, 1, 0, 1, 2)
        self.home_bar = QtWidgets.QFrame(parent=self.home_page)
        self.home_bar.setMinimumSize(QtCore.QSize(0, 66))
        self.home_bar.setMaximumSize(QtCore.QSize(16777215, 66))
        self.home_bar.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.home_bar.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.home_bar.setObjectName("home_bar")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.home_bar)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.home_search = QtWidgets.QLineEdit(parent=self.home_bar)
        self.home_search.setMinimumSize(QtCore.QSize(461, 40))
        self.home_search.setText("")
        self.home_search.setObjectName("home_search")
        self.horizontalLayout_4.addWidget(self.home_search)
        self.home_searchby = QtWidgets.QComboBox(parent=self.home_bar)
        self.home_searchby.setMinimumSize(QtCore.QSize(141, 40))
        self.home_searchby.setObjectName("home_searchby")
        self.home_searchby.addItem("")
        self.home_searchby.addItem("")
        self.home_searchby.addItem("")
        self.home_searchby.addItem("")
        self.horizontalLayout_4.addWidget(self.home_searchby)
        self.gridLayout_2.addWidget(self.home_bar, 0, 0, 1, 2)

        #Calendar Section
        self.home_calendar = QtWidgets.QCalendarWidget(parent=self.home_page)
        self.home_calendar.setMinimumSize(QtCore.QSize(441, 411))
        self.home_calendar.setVerticalHeaderFormat(
    QtWidgets.QCalendarWidget.VerticalHeaderFormat.NoVerticalHeader
)
        self.home_calendar.setObjectName("home_calendar")
        self.home_calendar.setStyleSheet("""
/* Base Calendar Styling */
QCalendarWidget {
    border-bottom-left-radius: 8px;
    border-bottom-right-radius: 8px;
    padding: 5px;
    font-family: "Poppins", sans-serif;
    font-size: 15px;
    background-color: white;
}

/* Navigation Bar */
QCalendarWidget QWidget#qt_calendar_navigationbar {
    background-color: #e2091e;
    border-top-left-radius: 8px;
    border-top-right-radius: 8px;
    color: white;
}

/* Date Cells */
QCalendarWidget QAbstractItemView {
    font-size: 15px;
    color: black;
    selection-background-color: #e2091e;
}

QCalendarWidget QAbstractItemView::header {
    background-color: #edf4fa; /* or any color you want */
}
                                         
QCalendarWidget QAbstractItemView:item:selected {
    background-color: #edf4fa !important;
    color: black !important;
    border: 2px solid #e2091e;
    border-radius: 3px;
}

/* Navigation Buttons */
QCalendarWidget QToolButton {
    background-color: #e2091e;
    color: white;
    font-family: "Poppins", sans-serif;
    font-weight: bold;
    border: none;
    border-radius: 8px;
    padding: 5px 8px;
    margin: 2px;
}
                                         
QCalendarWidget QToolButton QMenu {
    background-color: #e2091e;
    color: #FFFFFF;
    font-family: "Poppins", sans-serif;
    font-weight: normal;
    border-radius: 4px;
    padding: 5px;
}
                                        
QCalendarWidget QToolButton QMenu::item:selected {
    background-color: #b50817;
    border-radius: 4px;
}

/* Arrow Buttons */
QCalendarWidget QToolButton#qt_calendar_prevmonth,
QCalendarWidget QToolButton#qt_calendar_nextmonth {
    background-color: transparent;
    border: none;
}
                                         
/* Left arrow */
QCalendarWidget QToolButton#qt_calendar_prevmonth {
    qproperty-icon: url(icons/arrow-left-circle.svg);
    qproperty-iconSize: 25px 25px;
}
                                         
/* Right arrow */
QCalendarWidget QToolButton#qt_calendar_nextmonth {
    qproperty-icon: url(icons/arrow-right-circle.svg);
    qproperty-iconSize: 25px 25px;
}
""")
        self.gridLayout_2.addWidget(self.home_calendar, 2, 1, 1, 1)
        
        self.view_projects = QtWidgets.QFrame(parent=self.home_page)
        self.view_projects.setEnabled(True)
        self.view_projects.setMinimumSize(QtCore.QSize(441, 411))
        self.view_projects.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.view_projects.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.view_projects.setObjectName("view_projects")
        self.view_projects.setStyleSheet("""
            background-color: white;
            border-radius: 8px;
            border: none;
        """)

        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.view_projects)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.view_projects_label = QtWidgets.QLabel(parent=self.view_projects)
        self.view_projects_label.setMaximumSize(QtCore.QSize(237, 16777215))
        self.view_projects_label.setObjectName("view_projects_label")
        self.view_projects_label.setStyleSheet("font-size: 15pt; color: #7f00ff; margin-top: 10px;")
        self.verticalLayout_9.addWidget(self.view_projects_label)
        
        self.verticalLayout_9.addWidget(loadOnGoingProjects(self.view_projects))
        
        self.gridLayout_2.addWidget(self.view_projects, 2, 0, 1, 1)
        self.stackedWidget.addWidget(self.home_page)
        
        # Projects Page
        self.projects_page = QtWidgets.QWidget()
        self.projects_page.setObjectName("projects_page")
        
        # Grid layout for the projects page
        self.gridLayout_5 = QtWidgets.QGridLayout(self.projects_page)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setSpacing(10)
        self.gridLayout_5.setObjectName("gridLayout_5")
        
        # Projects bar at the top of the projects page
        self.projects_bar = QtWidgets.QFrame(parent=self.projects_page)
        self.projects_bar.setMinimumSize(QtCore.QSize(651, 66))
        self.projects_bar.setMaximumSize(QtCore.QSize(16777215, 66))
        self.projects_bar.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.projects_bar.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.projects_bar.setObjectName("projects_bar")
        
        # Horizontal layout for the projects bar
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.projects_bar)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        
        # Projects search input and buttons
        self.projects_search = QtWidgets.QLineEdit(parent=self.projects_bar)
        self.projects_search.setMinimumSize(QtCore.QSize(374, 40))
        self.projects_search.setText("")
        self.projects_search.setObjectName("projects_search")
        self.horizontalLayout_6.addWidget(self.projects_search)
        self.projects_searchby = QtWidgets.QComboBox(parent=self.projects_bar)
        self.projects_searchby.setMinimumSize(QtCore.QSize(141, 40))
        self.projects_searchby.setObjectName("projects_searchby")
        self.projects_searchby.addItem("")
        self.projects_searchby.addItem("")
        self.projects_searchby.addItem("")
        self.projects_searchby.addItem("")
        self.projects_searchby.addItem("")
        self.horizontalLayout_6.addWidget(self.projects_searchby)
        self.projects_sortby = QtWidgets.QComboBox(parent=self.projects_bar)
        self.projects_sortby.setMinimumSize(QtCore.QSize(141, 40))
        self.projects_sortby.setObjectName("projects_sortby")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icons/filter_gray.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.projects_sortby.addItem(icon5, "")
        self.projects_sortby.addItem("")
        self.projects_sortby.addItem("")
        self.projects_sortby.addItem("")
        self.projects_sortby.addItem("")
        self.horizontalLayout_6.addWidget(self.projects_sortby)
        self.addproject_button = QtWidgets.QPushButton(parent=self.projects_bar)
        self.addproject_button.setMinimumSize(QtCore.QSize(261, 0))
        self.addproject_button.setMaximumSize(QtCore.QSize(16777215, 40))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("icons/plus-circle.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.addproject_button.setIcon(icon6)
        self.addproject_button.setIconSize(QtCore.QSize(20, 20))
        self.addproject_button.setAutoRepeat(False)
        self.addproject_button.setObjectName("addproject_button")
        self.horizontalLayout_6.addWidget(self.addproject_button)
        self.gridLayout_5.addWidget(self.projects_bar, 0, 0, 1, 2)
        
        # Projects container with scroll area
        self.projects_container = QtWidgets.QFrame(parent=self.projects_page)
        self.projects_container.setMinimumSize(QtCore.QSize(681, 0))
        self.projects_container.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.projects_container.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.projects_container.setObjectName("projects_container")
        self.projects_container.setStyleSheet("""
            background-color: white;
            border-radius: 8px;
            border: none;
        """)
        
        # Horizontal layout for the projects container
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.projects_container)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.horizontalLayout_7.addWidget(loadProjects(self.projects_container)) #projects' page
        
        # Add the projects container to the grid layout
        self.gridLayout_5.addWidget(self.projects_container, 1, 0, 1, 1)
        
        # Project details section
        self.project_details = QtWidgets.QFrame(parent=self.projects_page)
        self.project_details.setMinimumSize(QtCore.QSize(271, 0))
        self.project_details.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.project_details.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.project_details.setObjectName("project_details")
        
        # Vertical layout for the project details
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.project_details)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        
        # Project details label
        self.project_details_label = QtWidgets.QLabel(parent=self.project_details)
        self.project_details_label.setMaximumSize(QtCore.QSize(16777215, 38))
        self.project_details_label.setObjectName("project_details_label")
        
        # Add the project details label to the vertical layout
        self.verticalLayout_4.addWidget(self.project_details_label)
        
        # Project details frame containing project information
        self.project_details_frame = QtWidgets.QFrame(parent=self.project_details)
        self.project_details_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.project_details_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.project_details_frame.setObjectName("project_details_frame")
        
        # Vertical layout for the project details frame
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.project_details_frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        
        # Adding project information labels to the vertical layout
        self.project_name = QtWidgets.QLabel(parent=self.project_details_frame)
        self.project_name.setObjectName("project_name")
        self.verticalLayout_3.addWidget(self.project_name)
        
        self.project_name_info = QtWidgets.QLabel(parent=self.project_details_frame)
        self.project_name_info.setText(f"")
        self.project_name_info.setObjectName("project_name_info")
        self.verticalLayout_3.addWidget(self.project_name_info)
        
        self.project_id = QtWidgets.QLabel(parent=self.project_details_frame)
        self.project_id.setObjectName("project_id")
        self.verticalLayout_3.addWidget(self.project_id)
        
        self.project_id_info = QtWidgets.QLabel(parent=self.project_details_frame)
        self.project_id_info.setText("")
        self.project_id_info.setObjectName("project_id_info")
        self.verticalLayout_3.addWidget(self.project_id_info)
        
        self.project_startDate = QtWidgets.QLabel(parent=self.project_details_frame)
        self.project_startDate.setObjectName("project_startDate")
        self.verticalLayout_3.addWidget(self.project_startDate)
        
        self.project_startDate_info = QtWidgets.QLabel(parent=self.project_details_frame)
        self.project_startDate_info.setText("")
        self.project_startDate_info.setObjectName("project_startDate_info")
        self.verticalLayout_3.addWidget(self.project_startDate_info)
        
        self.project_endDate = QtWidgets.QLabel(parent=self.project_details_frame)
        self.project_endDate.setObjectName("project_endDate")
        self.verticalLayout_3.addWidget(self.project_endDate)
        
        self.project_endDate_info = QtWidgets.QLabel(parent=self.project_details_frame)
        self.project_endDate_info.setText("")
        self.project_endDate_info.setObjectName("project_endDate_info")
        self.verticalLayout_3.addWidget(self.project_endDate_info)
        
        self.project_totalTasks = QtWidgets.QLabel(parent=self.project_details_frame)
        self.project_totalTasks.setObjectName("project_totalTasks")
        self.verticalLayout_3.addWidget(self.project_totalTasks)
        
        self.project_totalTasks_info = QtWidgets.QLabel(parent=self.project_details_frame)
        self.project_totalTasks_info.setText("")
        self.project_totalTasks_info.setObjectName("project_totalTasks_info")
        self.verticalLayout_3.addWidget(self.project_totalTasks_info)
        
        self.project_totalMembers = QtWidgets.QLabel(parent=self.project_details_frame)
        self.project_totalMembers.setObjectName("project_totalMembers")
        self.verticalLayout_3.addWidget(self.project_totalMembers)
        
        self.project_totalMembers_info = QtWidgets.QLabel(parent=self.project_details_frame)
        self.project_totalMembers_info.setText("")
        self.project_totalMembers_info.setObjectName("project_totalMembers_info")
        self.verticalLayout_3.addWidget(self.project_totalMembers_info)
        
        self.verticalLayout_4.addWidget(self.project_details_frame)
        
        
        self.project_expand_button = QtWidgets.QPushButton(parent=self.project_details)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("icons/maximize.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.project_expand_button.setIcon(icon7)
        self.project_expand_button.setObjectName("project_expand_button")
        self.verticalLayout_4.addWidget(self.project_expand_button)
        
        self.gridLayout_5.addWidget(self.project_details, 1, 1, 1, 1)
        
        self.stackedWidget.addWidget(self.projects_page)
        
        
        
        
        
        
        # Tasks Page
        self.tasks_page = QtWidgets.QWidget()
        self.tasks_page.setObjectName("tasks_page")
        
        # Grid layout for the tasks page
        self.gridLayout_10 = QtWidgets.QGridLayout(self.tasks_page)
        self.gridLayout_10.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_10.setSpacing(10)
        self.gridLayout_10.setObjectName("gridLayout_10")
        
        # Tasks bar at the top of the tasks page
        self.tasks_bar = QtWidgets.QFrame(parent=self.tasks_page)
        self.tasks_bar.setMinimumSize(QtCore.QSize(651, 66))
        self.tasks_bar.setMaximumSize(QtCore.QSize(16777215, 66))
        self.tasks_bar.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.tasks_bar.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.tasks_bar.setObjectName("tasks_bar")
        
        # Horizontal layout for the tasks bar
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.tasks_bar)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.tasks_search = QtWidgets.QLineEdit(parent=self.tasks_bar)
        self.tasks_search.setMinimumSize(QtCore.QSize(374, 40))
        self.tasks_search.setText("")
        self.tasks_search.setObjectName("tasks_search")
        self.horizontalLayout_13.addWidget(self.tasks_search)
        
        # Tasks search and sort options
        self.tasks_searchby = QtWidgets.QComboBox(parent=self.tasks_bar)
        self.tasks_searchby.setMinimumSize(QtCore.QSize(141, 40))
        self.tasks_searchby.setObjectName("tasks_searchby")
        self.tasks_searchby.addItem("")
        self.tasks_searchby.addItem("")
        self.tasks_searchby.addItem("")
        self.tasks_searchby.addItem("")
        self.tasks_searchby.addItem("")
        self.tasks_searchby.addItem("")
        self.tasks_searchby.addItem("")
        self.horizontalLayout_13.addWidget(self.tasks_searchby)
        
        # Tasks sort options
        self.tasks_sortby = QtWidgets.QComboBox(parent=self.tasks_bar)
        self.tasks_sortby.setMinimumSize(QtCore.QSize(141, 40))
        self.tasks_sortby.setObjectName("tasks_sortby")
        self.tasks_sortby.addItem(icon5, "")
        self.tasks_sortby.addItem("")
        self.tasks_sortby.addItem("")
        self.tasks_sortby.addItem("")
        self.tasks_sortby.addItem("")
        self.tasks_sortby.addItem("")
        self.tasks_sortby.addItem("")
        self.horizontalLayout_13.addWidget(self.tasks_sortby)
        
        # Button to add a new task
        self.addtask_button = QtWidgets.QPushButton(parent=self.tasks_bar)
        self.addtask_button.setMinimumSize(QtCore.QSize(261, 0))
        self.addtask_button.setMaximumSize(QtCore.QSize(16777215, 40))
        self.addtask_button.setIcon(icon6)
        self.addtask_button.setIconSize(QtCore.QSize(20, 20))
        self.addtask_button.setAutoRepeat(False)
        self.addtask_button.setObjectName("addtask_button")
        self.horizontalLayout_13.addWidget(self.addtask_button)
        
        # Add the tasks bar to the grid layout
        self.gridLayout_10.addWidget(self.tasks_bar, 0, 0, 1, 2)
        
        # Tasks container with scroll area
        self.tasks_container = QtWidgets.QFrame(parent=self.tasks_page)
        self.tasks_container.setMinimumSize(QtCore.QSize(681, 0))
        self.tasks_container.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.tasks_container.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.tasks_container.setObjectName("tasks_container")
        self.tasks_container.setStyleSheet("""
            background-color: white;
            border-radius: 8px;
            border: none;
        """)
        
        # Horizontal layout for the tasks container
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.tasks_container)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.horizontalLayout_14.addWidget(loadTasks(self.tasks_container))
        
        # Add the tasks container to the grid layout
        self.gridLayout_10.addWidget(self.tasks_container, 1, 0, 1, 1)
        
        # Task details section
        self.task_details = QtWidgets.QFrame(parent=self.tasks_page)
        self.task_details.setMinimumSize(QtCore.QSize(271, 0))
        self.task_details.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.task_details.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.task_details.setObjectName("task_details")
        
        # Vertical layout for the task details
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.task_details)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        
        # Task details label
        self.task_details_label = QtWidgets.QLabel(parent=self.task_details)
        self.task_details_label.setMaximumSize(QtCore.QSize(16777215, 38))
        self.task_details_label.setObjectName("task_details_label")
        self.verticalLayout_7.addWidget(self.task_details_label)
        
        # Task details frame containing task information
        self.task_details_frame = QtWidgets.QFrame(parent=self.task_details)
        self.task_details_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.task_details_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.task_details_frame.setObjectName("task_details_frame")
        
        # Vertical layout for the task details frame
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.task_details_frame)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        
        # Task Name Information
        self.task_name = QtWidgets.QLabel(parent=self.task_details_frame)
        self.task_name.setObjectName("task_name")
        self.verticalLayout_8.addWidget(self.task_name)
        self.task_name_info = QtWidgets.QLabel(parent=self.task_details_frame)
        self.task_name_info.setText("")
        self.task_name_info.setObjectName("task_name_info")
        self.verticalLayout_8.addWidget(self.task_name_info)
        
        # Task ID Information
        self.task_id = QtWidgets.QLabel(parent=self.task_details_frame)
        self.task_id.setObjectName("task_id")
        self.verticalLayout_8.addWidget(self.task_id)
        self.task_id_info = QtWidgets.QLabel(parent=self.task_details_frame)
        self.task_id_info.setText("")
        self.task_id_info.setObjectName("task_id_info")
        self.verticalLayout_8.addWidget(self.task_id_info)
        
        # Task Project Information
        self.task_project = QtWidgets.QLabel(parent=self.task_details_frame)
        self.task_project.setObjectName("task_project")
        self.verticalLayout_8.addWidget(self.task_project)
        self.task_project_info = QtWidgets.QLabel(parent=self.task_details_frame)
        self.task_project_info.setText("")
        self.task_project_info.setObjectName("task_project_info")
        self.verticalLayout_8.addWidget(self.task_project_info)
        
        # Task Status Information
        self.task_status = QtWidgets.QLabel(parent=self.task_details_frame)
        self.task_status.setObjectName("task_status")
        self.verticalLayout_8.addWidget(self.task_status)
        self.task_status_info = QtWidgets.QLabel(parent=self.task_details_frame)
        self.task_status_info.setText("")
        self.task_status_info.setObjectName("task_status_info")
        self.verticalLayout_8.addWidget(self.task_status_info)
        
        # Task Due Date Information
        self.task_dueDate = QtWidgets.QLabel(parent=self.task_details_frame)
        self.task_dueDate.setObjectName("task_dueDate")
        self.verticalLayout_8.addWidget(self.task_dueDate)
        self.task_dueDate_info = QtWidgets.QLabel(parent=self.task_details_frame)
        self.task_dueDate_info.setText("")
        self.task_dueDate_info.setObjectName("task_dueDate_info")
        self.verticalLayout_8.addWidget(self.task_dueDate_info)
        
        # Task Total Members Information
        self.task_totalMembers = QtWidgets.QLabel(parent=self.task_details_frame)
        self.task_totalMembers.setObjectName("task_totalMembers")
        self.verticalLayout_8.addWidget(self.task_totalMembers)
        self.task_totalMembers_info = QtWidgets.QLabel(parent=self.task_details_frame)
        self.task_totalMembers_info.setText("")
        self.task_totalMembers_info.setObjectName("task_totalMembers_info")
        self.verticalLayout_8.addWidget(self.task_totalMembers_info)
        
        # Add the task details frame to the vertical layout
        self.verticalLayout_7.addWidget(self.task_details_frame)
        
        self.task_expand_button = QtWidgets.QPushButton(parent=self.task_details)
        self.task_expand_button.setIcon(icon7)
        self.task_expand_button.setObjectName("task_expand_button")
        self.verticalLayout_7.addWidget(self.task_expand_button)
        self.gridLayout_10.addWidget(self.task_details, 1, 1, 1, 1)
        self.stackedWidget.addWidget(self.tasks_page)
        self.members_page = QtWidgets.QWidget()
        self.members_page.setObjectName("members_page")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.members_page)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setSpacing(10)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.members_bar = QtWidgets.QFrame(parent=self.members_page)
        self.members_bar.setMinimumSize(QtCore.QSize(651, 66))
        self.members_bar.setMaximumSize(QtCore.QSize(16777215, 66))
        self.members_bar.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.members_bar.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.members_bar.setObjectName("members_bar")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.members_bar)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.members_search = QtWidgets.QLineEdit(parent=self.members_bar)
        self.members_search.setMinimumSize(QtCore.QSize(374, 40))
        self.members_search.setText("")
        self.members_search.setObjectName("members_search")
        self.horizontalLayout_15.addWidget(self.members_search)
        self.members_searchby = QtWidgets.QComboBox(parent=self.members_bar)
        self.members_searchby.setMinimumSize(QtCore.QSize(141, 40))
        self.members_searchby.setObjectName("members_searchby")
        self.members_searchby.addItem("")
        self.members_searchby.addItem("")
        self.members_searchby.addItem("")
        self.members_searchby.addItem("")
        self.members_searchby.addItem("")
        self.members_searchby.addItem("")
        self.horizontalLayout_15.addWidget(self.members_searchby)
        self.addmember_button = QtWidgets.QPushButton(parent=self.members_bar)
        self.addmember_button.setMinimumSize(QtCore.QSize(261, 0))
        self.addmember_button.setMaximumSize(QtCore.QSize(16777215, 40))
        self.addmember_button.setIcon(icon6)
        self.addmember_button.setIconSize(QtCore.QSize(20, 20))
        self.addmember_button.setAutoRepeat(False)
        self.addmember_button.setObjectName("addmember_button")
        self.horizontalLayout_15.addWidget(self.addmember_button)
        self.verticalLayout_10.addWidget(self.members_bar)
        self.members_table_frame = QtWidgets.QFrame(parent=self.members_page)
        self.members_table_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.members_table_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.members_table_frame.setObjectName("members_table_frame")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.members_table_frame)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.members_table = QtWidgets.QTableWidget(parent=self.members_table_frame)
        self.members_table.setAlternatingRowColors(True)
        self.members_table.setObjectName("members_table")
        self.members_table.setColumnCount(5)
        self.members_table.setRowCount(0)


        #added lines to expand the table horizontally
        self.members_table.setSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        self.members_table.horizontalHeader().setStretchLastSection(True)
        self.members_table.horizontalHeader().setSectionResizeMode(QtWidgets.QHeaderView.ResizeMode.Stretch)
        self.members_table.verticalHeader().setVisible(False)
        self.members_table.verticalHeader().setDefaultSectionSize(0)  # Remove leftover space

        item = QtWidgets.QTableWidgetItem()
        self.members_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.members_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.members_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.members_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.members_table.setHorizontalHeaderItem(4, item)
        self.verticalLayout_11.addWidget(self.members_table)
        self.gridLayout_12.addLayout(self.verticalLayout_11, 0, 0, 1, 1)
        self.verticalLayout_10.addWidget(self.members_table_frame)
        self.stackedWidget.addWidget(self.members_page)
        self.gridLayout.addWidget(self.stackedWidget, 1, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        frames = [self.topbar, self.menu_board, self.home_bar,
                  self.view_projects, self.home_calendar,
                  self.projects_bar, self.projects_container, self.project_details,
                  self.tasks_bar, self.tasks_container, self.task_details,
                  self.members_bar, self.members_table_frame]
        for frame in frames:
            shadow = QGraphicsDropShadowEffect(frame)
            shadow.setBlurRadius(20)
            shadow.setOffset(0, 0)
            shadow.setColor(QColor(0, 0, 0, 80))
            frame.setGraphicsEffect(shadow)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.planado_title.setText(_translate("MainWindow", "Planado"))
        self.home_button.setText(_translate("MainWindow", "Home"))
        self.projects_button.setText(_translate("MainWindow", "Projects"))
        self.tasks_button.setText(_translate("MainWindow", "Tasks"))
        self.members_button.setText(_translate("MainWindow", "Members"))
        self.projects_total_label_2.setText(_translate("MainWindow", "projects"))
        self.projects_total_label.setText(_translate("MainWindow", "Projects"))
        self.projects_total_count.setText(_translate("MainWindow", "0"))
        self.tasks_total_label_2.setText(_translate("MainWindow", "tasks"))
        self.tasks_total_label.setText(_translate("MainWindow", "Tasks"))
        self.tasks_total_count.setText(_translate("MainWindow", "0"))
        self.members_total_label_2.setText(_translate("MainWindow", "members"))
        self.members_total_label.setText(_translate("MainWindow", "Members"))
        self.members_total_count.setText(_translate("MainWindow", "0"))
        self.home_search.setPlaceholderText(_translate("MainWindow", "Type to search..."))
        self.home_searchby.setItemText(0, _translate("MainWindow", "Search by"))
        self.home_searchby.setItemText(1, _translate("MainWindow", "Projects"))
        self.home_searchby.setItemText(2, _translate("MainWindow", "Tasks"))
        self.home_searchby.setItemText(3, _translate("MainWindow", "Members"))
        self.view_projects_label.setText(_translate("MainWindow", "    Ongoing Projects"))
        self.projects_search.setPlaceholderText(_translate("MainWindow", "Type to search..."))
        self.projects_searchby.setItemText(0, _translate("MainWindow", "Search by"))
        self.projects_searchby.setItemText(1, _translate("MainWindow", "Name"))
        self.projects_searchby.setItemText(2, _translate("MainWindow", "Project ID"))
        self.projects_searchby.setItemText(3, _translate("MainWindow", "Start Date"))
        self.projects_searchby.setItemText(4, _translate("MainWindow", "End Date"))
        self.projects_sortby.setItemText(0, _translate("MainWindow", "Sort by"))
        self.projects_sortby.setItemText(1, _translate("MainWindow", "Name"))
        self.projects_sortby.setItemText(2, _translate("MainWindow", "Project ID"))
        self.projects_sortby.setItemText(3, _translate("MainWindow", "Start Date"))
        self.projects_sortby.setItemText(4, _translate("MainWindow", "End Date"))
        self.addproject_button.setText(_translate("MainWindow", "Add Project"))
        self.project_details_label.setText(_translate("MainWindow", "Details"))
        self.project_name.setText(_translate("MainWindow", "Project Name:"))
        self.project_id.setText(_translate("MainWindow", "Project ID:"))
        self.project_startDate.setText(_translate("MainWindow", "Start Date:"))
        self.project_endDate.setText(_translate("MainWindow", "End Date:"))
        self.project_totalTasks.setText(_translate("MainWindow", "Total Tasks:"))
        self.project_totalMembers.setText(_translate("MainWindow", "Total Members:"))
        self.project_expand_button.setText(_translate("MainWindow", "Expand"))
        self.tasks_search.setPlaceholderText(_translate("MainWindow", "Type to search..."))
        self.tasks_searchby.setItemText(0, _translate("MainWindow", "Search by"))
        self.tasks_searchby.setItemText(1, _translate("MainWindow", "Name"))
        self.tasks_searchby.setItemText(2, _translate("MainWindow", "Task ID"))
        self.tasks_searchby.setItemText(3, _translate("MainWindow", "Project"))
        self.tasks_searchby.setItemText(4, _translate("MainWindow", "Status"))
        self.tasks_searchby.setItemText(5, _translate("MainWindow", "Due Date"))
        self.tasks_searchby.setItemText(6, _translate("MainWindow", "Date Accomplished"))
        self.tasks_sortby.setItemText(0, _translate("MainWindow", "Sort by"))
        self.tasks_sortby.setItemText(1, _translate("MainWindow", "Name"))
        self.tasks_sortby.setItemText(2, _translate("MainWindow", "Task ID"))
        self.tasks_sortby.setItemText(3, _translate("MainWindow", "Project"))
        self.tasks_sortby.setItemText(4, _translate("MainWindow", "Status"))
        self.tasks_sortby.setItemText(5, _translate("MainWindow", "Due Date"))
        self.tasks_sortby.setItemText(6, _translate("MainWindow", "Date Accomplished"))
        self.addtask_button.setText(_translate("MainWindow", "Add Task"))
        self.task_details_label.setText(_translate("MainWindow", "Details"))
        self.task_name.setText(_translate("MainWindow", "Task Name:"))
        self.task_id.setText(_translate("MainWindow", "Task ID:"))
        self.task_project.setText(_translate("MainWindow", "Project:"))
        self.task_status.setText(_translate("MainWindow", "Status:"))
        self.task_dueDate.setText(_translate("MainWindow", "Due Date:"))
        self.task_totalMembers.setText(_translate("MainWindow", "Total Members:"))
        self.task_expand_button.setText(_translate("MainWindow", "Expand"))
        self.members_search.setPlaceholderText(_translate("MainWindow", "Type to search..."))
        self.members_searchby.setItemText(0, _translate("MainWindow", "Search by"))
        self.members_searchby.setItemText(1, _translate("MainWindow", "Member ID"))
        self.members_searchby.setItemText(2, _translate("MainWindow", "Name"))
        self.members_searchby.setItemText(3, _translate("MainWindow", "Email"))
        self.members_searchby.setItemText(4, _translate("MainWindow", "Project"))
        self.members_searchby.setItemText(5, _translate("MainWindow", "Task"))
        self.addmember_button.setText(_translate("MainWindow", "Add Member"))
        item = self.members_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Member ID"))
        item = self.members_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name"))
        item = self.members_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Email"))
        item = self.members_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Projects"))
        item = self.members_table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Tasks"))
