# Form implementation generated from reading ui file 'tasks_expand.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QGraphicsDropShadowEffect
from PyQt6.QtGui import QColor

class Ui_tasks_expand(object):
    def setupUi(self, tasks_expand):
        tasks_expand.setObjectName("tasks_expand")
        tasks_expand.resize(643, 602)
        tasks_expand.setStyleSheet("QDialog{\n"
"    background-color: #edf4fa;\n"
"}\n"
"\n"
"QFrame {\n"
"    background-color: #FFFFFF;\n"
"    border: 1px solid #FFFFFF;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QLabel \n"
"    font-family: \"Poppins\", sans-serif;\n"
"    font-size: 15px;\n"
"    color: #000000;\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"#task_id, #task_project, #task_status, #task_dueDate, #task_dateAccomplished, #task_shortDescrip, #task_members {\n"
"    font-family: \"Poppins\", sans-serif;\n"
"    font-weight: bold;\n"
"    font-size: 9pt;\n"
"    color: #92979d;\n"
"}\n"
"\n"
"QTextEdit, QListWidget {\n"
"    font-family: \"Poppins\", sans-serif;\n"
"    font-weight: normal;\n"
"    font-size: 10pt;\n"
"    color: #000000;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #fe9137;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    color: #FFFFFF;\n"
"    text-align: center;\n"
"    font-family: \"Poppins\", sans-serif;\n"
"    font-size: 15px;\n"
"    padding: 8px;\n"
"}\n"
"\n"
"#task_id_icon, #task_project_icon, #task_status_icon, #task_dueDate_icon, #task_dateAccomplished_icon, #task_shortDescrip_icon, #task_members_icon {\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"#task_update_button, #task_delete_button {\n"
"    font-size: 10pt;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"Line {\n"
"    background-color: #c2c6cc;\n"
"}\n"
"\n"
"#task_name {\n"
"    font-size: 20pt;\n"
"    font-weight: bold;\n"
"    color: #fe9137;\n"
"}\n"
"\n"
"#task_id_info, #task_dueDate_info, #task_dateAccomplished_info, #task_project_info, #task_status_info, #task_dateAccomplished_info, #task_shortDescrip_info, #task_members_info{\n"
"    font-family: \"Poppins\", sans-serif;\n"
"    font-weight: normal;\n"
"    font-size: 10pt;\n"
"    color: #000000;\n"
"}")
        self.gridLayout = QtWidgets.QGridLayout(tasks_expand)
        self.gridLayout.setContentsMargins(15, 15, 15, 15)
        self.gridLayout.setSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.tasks_expand_frame = QtWidgets.QFrame(parent=tasks_expand)
        self.tasks_expand_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.tasks_expand_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.tasks_expand_frame.setObjectName("tasks_expand_frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tasks_expand_frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_7 = QtWidgets.QFrame(parent=self.tasks_expand_frame)
        self.frame_7.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.task_name_frame = QtWidgets.QFrame(parent=self.frame_7)
        self.task_name_frame.setMinimumSize(QtCore.QSize(450, 61))
        self.task_name_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.task_name_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.task_name_frame.setObjectName("task_name_frame")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.task_name_frame)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setSpacing(0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.task_name = QtWidgets.QLabel(parent=self.task_name_frame)
        self.task_name.setObjectName("task_name")
        self.gridLayout_6.addWidget(self.task_name, 0, 0, 1, 1)
        self.horizontalLayout_5.addWidget(self.task_name_frame)
        self.task_updateDelete = QtWidgets.QFrame(parent=self.frame_7)
        self.task_updateDelete.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.task_updateDelete.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.task_updateDelete.setObjectName("task_updateDelete")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.task_updateDelete)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.task_update_button = QtWidgets.QPushButton(parent=self.task_updateDelete)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/edit.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.task_update_button.setIcon(icon)
        self.task_update_button.setObjectName("task_update_button")
        self.verticalLayout_2.addWidget(self.task_update_button)
        self.task_delete_button = QtWidgets.QPushButton(parent=self.task_updateDelete)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/trash-2.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.task_delete_button.setIcon(icon1)
        self.task_delete_button.setObjectName("task_delete_button")
        self.verticalLayout_2.addWidget(self.task_delete_button)
        self.horizontalLayout_5.addWidget(self.task_updateDelete)
        self.verticalLayout_3.addWidget(self.frame_7)
        self.hline = QtWidgets.QFrame(parent=self.tasks_expand_frame)
        self.hline.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.hline.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.hline.setObjectName("hline")
        self.verticalLayout_3.addWidget(self.hline)
        self.task_id_frame = QtWidgets.QFrame(parent=self.tasks_expand_frame)
        self.task_id_frame.setMinimumSize(QtCore.QSize(0, 41))
        self.task_id_frame.setMaximumSize(QtCore.QSize(16777215, 41))
        self.task_id_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.task_id_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.task_id_frame.setObjectName("task_id_frame")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.task_id_frame)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setSpacing(20)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.task_id_label = QtWidgets.QFrame(parent=self.task_id_frame)
        self.task_id_label.setMinimumSize(QtCore.QSize(215, 41))
        self.task_id_label.setMaximumSize(QtCore.QSize(215, 41))
        self.task_id_label.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.task_id_label.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.task_id_label.setObjectName("task_id_label")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.task_id_label)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.task_id_icon = QtWidgets.QPushButton(parent=self.task_id_label)
        self.task_id_icon.setMinimumSize(QtCore.QSize(20, 20))
        self.task_id_icon.setMaximumSize(QtCore.QSize(20, 20))
        self.task_id_icon.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/key_gray.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.task_id_icon.setIcon(icon2)
        self.task_id_icon.setObjectName("task_id_icon")
        self.horizontalLayout.addWidget(self.task_id_icon)
        self.task_id = QtWidgets.QLabel(parent=self.task_id_label)
        self.task_id.setObjectName("task_id")
        self.horizontalLayout.addWidget(self.task_id)
        self.horizontalLayout_15.addWidget(self.task_id_label)
        self.task_id_info = QtWidgets.QLabel(parent=self.task_id_frame)
        self.task_id_info.setText("")
        self.task_id_info.setObjectName("task_id_info")
        self.horizontalLayout_15.addWidget(self.task_id_info)
        self.verticalLayout_3.addWidget(self.task_id_frame)
        self.task_project_frame = QtWidgets.QFrame(parent=self.tasks_expand_frame)
        self.task_project_frame.setMinimumSize(QtCore.QSize(0, 41))
        self.task_project_frame.setMaximumSize(QtCore.QSize(16777215, 41))
        self.task_project_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.task_project_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.task_project_frame.setObjectName("task_project_frame")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.task_project_frame)
        self.horizontalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_20.setSpacing(20)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.task_project_label = QtWidgets.QFrame(parent=self.task_project_frame)
        self.task_project_label.setMinimumSize(QtCore.QSize(215, 41))
        self.task_project_label.setMaximumSize(QtCore.QSize(215, 41))
        self.task_project_label.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.task_project_label.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.task_project_label.setObjectName("task_project_label")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.task_project_label)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.task_project_icon = QtWidgets.QPushButton(parent=self.task_project_label)
        self.task_project_icon.setMinimumSize(QtCore.QSize(20, 20))
        self.task_project_icon.setMaximumSize(QtCore.QSize(20, 20))
        self.task_project_icon.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/folder_gray.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.task_project_icon.setIcon(icon3)
        self.task_project_icon.setObjectName("task_project_icon")
        self.horizontalLayout_2.addWidget(self.task_project_icon)
        self.task_project = QtWidgets.QLabel(parent=self.task_project_label)
        self.task_project.setObjectName("task_project")
        self.horizontalLayout_2.addWidget(self.task_project)
        self.horizontalLayout_20.addWidget(self.task_project_label)
        self.task_project_info = QtWidgets.QLabel(parent=self.task_project_frame)
        self.task_project_info.setText("")
        self.task_project_info.setObjectName("task_project_info")
        self.horizontalLayout_20.addWidget(self.task_project_info)
        self.verticalLayout_3.addWidget(self.task_project_frame)
        self.task_status_frame = QtWidgets.QFrame(parent=self.tasks_expand_frame)
        self.task_status_frame.setMinimumSize(QtCore.QSize(0, 41))
        self.task_status_frame.setMaximumSize(QtCore.QSize(16777215, 41))
        self.task_status_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.task_status_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.task_status_frame.setObjectName("task_status_frame")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.task_status_frame)
        self.horizontalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_21.setSpacing(20)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.task_status_label = QtWidgets.QFrame(parent=self.task_status_frame)
        self.task_status_label.setMinimumSize(QtCore.QSize(215, 41))
        self.task_status_label.setMaximumSize(QtCore.QSize(215, 41))
        self.task_status_label.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.task_status_label.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.task_status_label.setObjectName("task_status_label")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.task_status_label)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.task_status_icon = QtWidgets.QPushButton(parent=self.task_status_label)
        self.task_status_icon.setMinimumSize(QtCore.QSize(20, 20))
        self.task_status_icon.setMaximumSize(QtCore.QSize(20, 20))
        self.task_status_icon.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/circle_gray.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.task_status_icon.setIcon(icon4)
        self.task_status_icon.setObjectName("task_status_icon")
        self.horizontalLayout_3.addWidget(self.task_status_icon)
        self.task_status = QtWidgets.QLabel(parent=self.task_status_label)
        self.task_status.setObjectName("task_status")
        self.horizontalLayout_3.addWidget(self.task_status)
        self.horizontalLayout_21.addWidget(self.task_status_label)
        self.task_status_info = QtWidgets.QLabel(parent=self.task_status_frame)
        self.task_status_info.setText("")
        self.task_status_info.setObjectName("task_status_info")
        self.horizontalLayout_21.addWidget(self.task_status_info)
        self.verticalLayout_3.addWidget(self.task_status_frame)
        self.task_dueDate_frame = QtWidgets.QFrame(parent=self.tasks_expand_frame)
        self.task_dueDate_frame.setMinimumSize(QtCore.QSize(0, 41))
        self.task_dueDate_frame.setMaximumSize(QtCore.QSize(16777215, 41))
        self.task_dueDate_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.task_dueDate_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.task_dueDate_frame.setObjectName("task_dueDate_frame")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.task_dueDate_frame)
        self.horizontalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_16.setSpacing(20)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.task_dueDate_label = QtWidgets.QFrame(parent=self.task_dueDate_frame)
        self.task_dueDate_label.setMinimumSize(QtCore.QSize(215, 41))
        self.task_dueDate_label.setMaximumSize(QtCore.QSize(215, 41))
        self.task_dueDate_label.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.task_dueDate_label.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.task_dueDate_label.setObjectName("task_dueDate_label")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.task_dueDate_label)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.task_dueDate_icon = QtWidgets.QPushButton(parent=self.task_dueDate_label)
        self.task_dueDate_icon.setMinimumSize(QtCore.QSize(20, 20))
        self.task_dueDate_icon.setMaximumSize(QtCore.QSize(20, 20))
        self.task_dueDate_icon.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icons/calendar_gray.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.task_dueDate_icon.setIcon(icon5)
        self.task_dueDate_icon.setObjectName("task_dueDate_icon")
        self.horizontalLayout_4.addWidget(self.task_dueDate_icon)
        self.task_dueDate = QtWidgets.QLabel(parent=self.task_dueDate_label)
        self.task_dueDate.setObjectName("task_dueDate")
        self.horizontalLayout_4.addWidget(self.task_dueDate)
        self.horizontalLayout_16.addWidget(self.task_dueDate_label)
        self.task_dueDate_info = QtWidgets.QLabel(parent=self.task_dueDate_frame)
        self.task_dueDate_info.setText("")
        self.task_dueDate_info.setObjectName("task_dueDate_info")
        self.horizontalLayout_16.addWidget(self.task_dueDate_info)
        self.verticalLayout_3.addWidget(self.task_dueDate_frame)
        self.task_dateAccomplished_frame = QtWidgets.QFrame(parent=self.tasks_expand_frame)
        self.task_dateAccomplished_frame.setMinimumSize(QtCore.QSize(0, 41))
        self.task_dateAccomplished_frame.setMaximumSize(QtCore.QSize(16777215, 41))
        self.task_dateAccomplished_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.task_dateAccomplished_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.task_dateAccomplished_frame.setObjectName("task_dateAccomplished_frame")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.task_dateAccomplished_frame)
        self.horizontalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_17.setSpacing(20)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.task_dateAccomplished_label = QtWidgets.QFrame(parent=self.task_dateAccomplished_frame)
        self.task_dateAccomplished_label.setMinimumSize(QtCore.QSize(215, 41))
        self.task_dateAccomplished_label.setMaximumSize(QtCore.QSize(215, 41))
        self.task_dateAccomplished_label.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.task_dateAccomplished_label.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.task_dateAccomplished_label.setObjectName("task_dateAccomplished_label")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.task_dateAccomplished_label)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.task_dateAccomplished_icon = QtWidgets.QPushButton(parent=self.task_dateAccomplished_label)
        self.task_dateAccomplished_icon.setMinimumSize(QtCore.QSize(20, 20))
        self.task_dateAccomplished_icon.setMaximumSize(QtCore.QSize(20, 20))
        self.task_dateAccomplished_icon.setText("")
        self.task_dateAccomplished_icon.setIcon(icon5)
        self.task_dateAccomplished_icon.setObjectName("task_dateAccomplished_icon")
        self.horizontalLayout_7.addWidget(self.task_dateAccomplished_icon)
        self.task_dateAccomplished = QtWidgets.QLabel(parent=self.task_dateAccomplished_label)
        self.task_dateAccomplished.setObjectName("task_dateAccomplished")
        self.horizontalLayout_7.addWidget(self.task_dateAccomplished)
        self.horizontalLayout_17.addWidget(self.task_dateAccomplished_label)
        self.task_dateAccomplished_info = QtWidgets.QLabel(parent=self.task_dateAccomplished_frame)
        self.task_dateAccomplished_info.setText("")
        self.task_dateAccomplished_info.setObjectName("task_dateAccomplished_info")
        self.horizontalLayout_17.addWidget(self.task_dateAccomplished_info)
        self.verticalLayout_3.addWidget(self.task_dateAccomplished_frame)
        self.task_shortDescrip_frame = QtWidgets.QFrame(parent=self.tasks_expand_frame)
        self.task_shortDescrip_frame.setMinimumSize(QtCore.QSize(0, 80))
        self.task_shortDescrip_frame.setMaximumSize(QtCore.QSize(16777215, 80))
        self.task_shortDescrip_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.task_shortDescrip_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.task_shortDescrip_frame.setObjectName("task_shortDescrip_frame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.task_shortDescrip_frame)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setHorizontalSpacing(20)
        self.gridLayout_4.setVerticalSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.task_shortDescrip_label = QtWidgets.QFrame(parent=self.task_shortDescrip_frame)
        self.task_shortDescrip_label.setMinimumSize(QtCore.QSize(215, 41))
        self.task_shortDescrip_label.setMaximumSize(QtCore.QSize(215, 41))
        self.task_shortDescrip_label.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.task_shortDescrip_label.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.task_shortDescrip_label.setObjectName("task_shortDescrip_label")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.task_shortDescrip_label)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.task_shortDescrip_icon = QtWidgets.QPushButton(parent=self.task_shortDescrip_label)
        self.task_shortDescrip_icon.setMinimumSize(QtCore.QSize(20, 20))
        self.task_shortDescrip_icon.setMaximumSize(QtCore.QSize(20, 20))
        self.task_shortDescrip_icon.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("icons/edit-3_gray.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.task_shortDescrip_icon.setIcon(icon6)
        self.task_shortDescrip_icon.setObjectName("task_shortDescrip_icon")
        self.horizontalLayout_11.addWidget(self.task_shortDescrip_icon)
        self.task_shortDescrip = QtWidgets.QLabel(parent=self.task_shortDescrip_label)
        self.task_shortDescrip.setObjectName("task_shortDescrip")
        self.horizontalLayout_11.addWidget(self.task_shortDescrip)
        self.gridLayout_4.addWidget(self.task_shortDescrip_label, 0, 0, 1, 1)
        self.frame_4 = QtWidgets.QFrame(parent=self.task_shortDescrip_frame)
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_4.addWidget(self.frame_4, 1, 0, 1, 1)
        self.task_shortDescrip_info = QtWidgets.QTextEdit(parent=self.task_shortDescrip_frame)
        self.task_shortDescrip_info.setReadOnly(True)
        self.task_shortDescrip_info.setPlaceholderText("")
        self.task_shortDescrip_info.setObjectName("task_shortDescrip_info")
        self.gridLayout_4.addWidget(self.task_shortDescrip_info, 0, 1, 2, 1)
        self.verticalLayout_3.addWidget(self.task_shortDescrip_frame)
        self.task_members_frame = QtWidgets.QFrame(parent=self.tasks_expand_frame)
        self.task_members_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.task_members_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.task_members_frame.setObjectName("task_members_frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.task_members_frame)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setHorizontalSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.task_members_label = QtWidgets.QFrame(parent=self.task_members_frame)
        self.task_members_label.setMinimumSize(QtCore.QSize(151, 41))
        self.task_members_label.setMaximumSize(QtCore.QSize(151, 41))
        self.task_members_label.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.task_members_label.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.task_members_label.setObjectName("task_members_label")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.task_members_label)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.task_members_icon = QtWidgets.QPushButton(parent=self.task_members_label)
        self.task_members_icon.setMinimumSize(QtCore.QSize(20, 20))
        self.task_members_icon.setMaximumSize(QtCore.QSize(20, 20))
        self.task_members_icon.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("icons/users_gray.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.task_members_icon.setIcon(icon7)
        self.task_members_icon.setObjectName("task_members_icon")
        self.horizontalLayout_14.addWidget(self.task_members_icon)
        self.task_members = QtWidgets.QLabel(parent=self.task_members_label)
        self.task_members.setObjectName("task_members")
        self.horizontalLayout_14.addWidget(self.task_members)
        self.gridLayout_3.addWidget(self.task_members_label, 0, 0, 1, 2)
        self.frame_3 = QtWidgets.QFrame(parent=self.task_members_frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_3.addWidget(self.frame_3, 0, 2, 1, 1)
        self.frame_6 = QtWidgets.QFrame(parent=self.task_members_frame)
        self.frame_6.setMinimumSize(QtCore.QSize(35, 0))
        self.frame_6.setMaximumSize(QtCore.QSize(35, 16777215))
        self.frame_6.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_6.setObjectName("frame_6")
        self.gridLayout_3.addWidget(self.frame_6, 1, 0, 1, 1)
        self.task_members_info = QtWidgets.QListWidget(parent=self.task_members_frame)
        self.task_members_info.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.task_members_info.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.NoSelection)
        self.task_members_info.setObjectName("task_members_info")
        self.gridLayout_3.addWidget(self.task_members_info, 1, 1, 1, 2)
        self.verticalLayout_3.addWidget(self.task_members_frame)
        self.gridLayout.addWidget(self.tasks_expand_frame, 0, 0, 1, 1)

        frames = [self.tasks_expand_frame]
        for frame in frames:
            shadow = QGraphicsDropShadowEffect(frame)
            shadow.setBlurRadius(20)
            shadow.setOffset(0, 0)
            shadow.setColor(QColor(0, 0, 0, 80))
            frame.setGraphicsEffect(shadow)

        self.retranslateUi(tasks_expand)
        QtCore.QMetaObject.connectSlotsByName(tasks_expand)

    def retranslateUi(self, tasks_expand):
        _translate = QtCore.QCoreApplication.translate
        tasks_expand.setWindowTitle(_translate("tasks_expand", "Dialog"))
        self.task_name.setText(_translate("tasks_expand", "Task Name"))
        self.task_update_button.setText(_translate("tasks_expand", "Update"))
        self.task_delete_button.setText(_translate("tasks_expand", "Delete"))
        self.task_id.setText(_translate("tasks_expand", "Task ID"))
        self.task_project.setText(_translate("tasks_expand", "Project"))
        self.task_status.setText(_translate("tasks_expand", "Status"))
        self.task_dueDate.setText(_translate("tasks_expand", "Due Date"))
        self.task_dateAccomplished.setText(_translate("tasks_expand", "Date Accomplished"))
        self.task_shortDescrip.setText(_translate("tasks_expand", "Description"))
        self.task_shortDescrip_info.setHtml(_translate("tasks_expand", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Poppins,sans-serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.task_members.setText(_translate("tasks_expand", "Members"))
